### ISSUE TITLE
v2.8.2: ShareInto/QuickNote Markor not saving

### ISSUE THREAD

**Issue by Ssmur** [gsantner/markor#1482] opened 2021-11-04 15:26 UTC
## General information
* App version: 2.8.2 (F-Droid)
* Android version: 8.1
* Device: OnePlus 5T
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

Today I've updated Markor (2.8.1) to (2.8.2).
 In Firefox, press Share button to save URL, paste the note on a large file I have of links saved, and Markor when ask where to insert the note, I choose that file (bookmarksff.md) and open the file cmpletly erased everything, 0 bytes.  I have create other dummy file (markdown), write something random, Save, close file and open it again, there are the text. I repeat the process of save a Url from Firefox to Markor and choose that dummy file, and again, the file auto-delete its content, does not even enter the Url I want to save.
I wil try with a Xiaomi 6a, and update the result.

**[UPDATE]** Well, in a Xiaomi 6a  Stock rom MIUI 11.0.8 reproduces the same behaviour. In this  case, I open a app of F-Droid catalog, press ShareInto button, select Markor, select file of notes and got erased its  content.

**Comment by gsantner** [comment] 2021-11-04 16:07
pronably from #1473 , though using this a lot haven't seen it yet

**Comment by harshad1** [comment] 2021-11-04 17:42
Relevant code 

https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/activity/DocumentShareIntoFragment.java#L203-L220

I don't see an obvious bug in the code

**Comment by gsantner** [comment] 2021-11-04 17:44
I'm setting up android dev on a new OS. As far I read there is also an issue with QuickNote/todo.txt/Main page, so might be outside the ShareIntoFragment

**Comment by harshad1** [comment] 2021-11-04 17:49
On fail we return content = ""

https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/model/Document.java#L230-L231

I think it would be better to not hide the exception and force the calling code to handle an exception. That way, we can prevent writes if there was an exception on read.

**Comment by harshad1** [comment] 2021-11-04 17:53
I can reproduce this issue. Happens with encrypted files.

**Comment by gsantner** [comment] 2021-11-04 17:55
hehe, once more "we don't save empty files, too much tears about lost files" :smiley:

**Comment by harshad1** [comment] 2021-11-04 17:56
> hehe, once more "we don't save empty files, too much tears about lost files" 😃

Sigh.

**Comment by harshad1** [comment] 2021-11-04 17:58
I'll look into solving the root cause in the evening

Will also add the empty files logic back in

**Comment by gsantner** [comment] 2021-11-04 17:59
thanks for your quick help

I finished downloading android sdk now ...  also working on it

**Comment by harshad1** [comment] 2021-11-04 18:01
![image](https://user-images.githubusercontent.com/1940940/140394367-e23b3880-a39f-4c8f-b311-9c41c3e02531.png)

What is going on? I don't see any deleted comments?

**Comment by gsantner** [comment] 2021-11-04 19:03
@harshad1   
hmm, I have the current master  installed, however sharing into works, no loss at quicknote/todo, and also not when normal opening/closing a file.  
I could reproduce it in the build I had before though

**Comment by gsantner** [comment] 2021-11-04 19:15
@harshad1   
hmm, I have the current master  installed, however sharing into works, no loss at quicknote/todo, and also not when normal opening/closing a file.  

I can only reproduce an issue when selecting some a file from filemanager in the popup dialog, from i.e. recent/popular files.  So what @Ssmur  described, but not #1483 


https://user-images.githubusercontent.com/6735650/140404477-9cf59f3c-5ea5-44b6-ab64-4c46c3f540e5.mp4

**Comment by gsantner** [comment] 2021-11-04 19:33
@Ssmur @kylesorkness  
Can you please try the build of this app, and check if the issue is still present? The download button is the   
`android-apk`, below `all`. The app is a debug build which can be installed **beside** Markor, and is named **Mordor**.  
(For testing, ShareInto Mordor)

<https://github.com/gsantner/markor/actions/runs/1422885489>

**Comment by harshad1** [comment] 2021-11-04 19:33
Yeah. I am seeing this too.

It may be possible to address this by making the IO functions static? That way the `synchronized` will not be instance specific.

**Comment by gsantner** [comment] 2021-11-04 19:37
new insight: document is transferred from ShareInto, it has modTime set from the time of adding the additional text. when file call is running at the DocumentEditor, it sees file was already read and it ignores to re-read again (per se ok, just that the texteditor is empty, and no file is read) ---> added resetting of modTime prior passing on to DocumentEditor initializer.

**Comment by gsantner** [comment] 2021-11-04 19:38
new insight: document is transferred from ShareInto, it has modTime set from the time of adding the additional text. when document.read call is running at the DocumentEditor, it sees file was already read (modTime == current file.modTime()) and it not read again as expected. (Per se ok, just that the texteditor is empty, and no file was read previously at this editor) ---> added resetting of modTime prior passing on to DocumentEditor initializer.

**Comment by Ssmur** [comment] 2021-11-04 23:07
@gsantner @harshad1 
Hi, good news, I tested the build you posted. And now doing the same, does not erase the text saved previously.
I have repeated three times the steps for make sure the bug it's fixed. Included saving in Quicknote, To-Do and custom file.
Seems fixed to me.

**Comment by harshad1** [comment] 2021-11-22 20:11
@gsantner This is now solved right?

**Closed** 2021-11-22 21:14 UTC
Labels: bug
