### ISSUE TITLE
remember the last selected format for a file

### ISSUE THREAD

**Issue by gsantner** [gsantner/markor#845] opened 2020-02-03 10:58 UTC
<https://friendica.feneas.org/display/24324cc4f78a52dad488dfa76a302a2230da0053>

![grafik](https://user-images.githubusercontent.com/6735650/73647691-f0998e00-4673-11ea-8f51-730a9643c796.png)

it would be great if #markor remembered the last selected format for a file. #featurerequest

E.g., I use different #todotxt files, including a `today.txt`, but every time I open it I have to re-select the todo.txt format.

**Comment by macdonaldster** [comment] 2020-02-03 11:52
Hi, I believe you can use filenames for this. For example, naming your file "today.todo.txt" should do what you want.

I do this using the ".md" extension (e.g. "file.md.txt") because I use a desktop editor that will only look at ".txt" files but I want them treated as Markdown by Markor.

**Comment by macdonaldster** [comment] 2020-02-03 11:54
Duplicate of #805?

**Comment by gsantner** [comment] 2020-02-09 10:17
@macdonaldster 
In this case the user may want to have a custom format remembered for the current file. While the intention is quite same, it's still right that there should be a way to remember set type.

**Closed** 2020-05-02 13:53 UTC
Labels: enhancement, good first issue, hacktoberfest, help wanted
