### ISSUE TITLE
Clicking on recent button crashes app.

### ISSUE THREAD

**Issue by kaeza** [gsantner/markor#272] opened 2018-06-01 18:02 UTC
```
java.lang.IndexOutOfBoundsException: setSpan (-1 ... 0) starts before 0
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1095)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
	at net.gsantner.markor.ui.SearchOrCustomTextDialogCreator.showRecentDocumentsDialog(SearchOrCustomTextDialogCreator.java:59)
	at net.gsantner.markor.activity.MainActivity.onOptionsItemSelected(MainActivity.java:165)
	at android.app.Activity.onMenuItemSelected(Activity.java:2963)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:407)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:63)
	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
	at android.view.View.performClick(View.java:5207)
	at android.view.View$PerformClick.run(View.java:21177)
	at android.os.Handler.handleCallback(Handler.java:742)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:5523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
```

**Comment by kRkk** [comment] 2018-06-01 18:06
Duplicate of #271

**Closed** 2018-06-01 18:21 UTC
