### ISSUE TITLE
Bug Report: Delayed Appearance of Newly Created Folders

### ISSUE THREAD

**Issue by XYIheng** [gsantner/markor#2250] opened 2024-03-27 12:39 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

In the markor, when creating a new folder, the new folder does not appear immediately. The delayed appearance of the newly created folder causes confusion and disrupts the expected user experience.

### Steps to reproduce

1. click FAB
2. rotate device 
3. enter the folder name
4. click Folder
5. see error: the created folder doesn't appear, and you need to refresh the app to let the folder appear

https://github.com/gsantner/markor/assets/31406320/1e2c8617-e084-4b71-945e-841e6f7d1198

### Information

Android version: Android 10
Device: pixel2 and pixel 7
App Version: 2.11.1

### Source

F-Droid

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment] 2024-03-27 17:59
please download test builds from https://github.com/gsantner/markor/actions?query=branch%3Amaster+actor%3Agsantner if you didnt already - click the latest build and you can find a android-apk button to download.

Is it better in Marder?

**Comment by XYIheng** [comment] 2024-03-27 18:10
@gsantner Hi, I just download the latest build apk from your link and find the bug still exists

**Comment by gsantner** [comment] 2024-03-27 18:36
In Marder? (If you check Markor you dont use the version from that apk)

**Comment by XYIheng** [comment] 2024-03-28 12:38
@gsantner Yes, in Marder.
![image](https://github.com/gsantner/markor/assets/31406320/e8b55374-bb3d-4b5c-86d2-125a5710c0cd)

**Comment by XYIheng** [comment] 2024-03-28 15:21
https://github.com/gsantner/markor/assets/31406320/95a0a5e2-5c90-4f30-9a8c-fa258c696568

Also not work when try to create new files

**Comment by gsantner** [comment] 2024-03-28 19:30
Humbly said, I can't reproduce on neither release nor testversion. New stuff shows up after accepting.

**Comment by gsantner** [comment] 2024-03-28 19:30
Humbly said, I can not reproduce on release nor testversion. New stuff shows up after accepting.

**Comment by XYIheng** [comment] 2024-04-03 11:11
> Humbly said, I can not reproduce on release nor testversion. New stuff shows up after accepting.

Hi, I downloaded Marder from this link https://github.com/gsantner/markor/actions/runs/8483832311
And tested it on my real device: Xiaomi 10s, MIUI14.0.6.
The bug still exists

**Comment by XixianLiang** [comment] 2024-04-03 11:36
I can also reproduce this bug.

HUAWEI HONER
Android: 12
OS: MagicOS 7.0
Model: AGT-AN00

**Comment by gsantner** [comment] 2024-04-03 19:46
Feel free to fix the issue and create a merge request. Thanks!

**Comment by harshad1** [comment] 2024-04-21 03:44
I have traced this bug.

We pass a callback into the NewFileDialog to be triggered when the dialog completes. Upon rotation, the dialog is recreated and the callback is invalidated. 

We need to either preserve the callback (difficult) or change how we trigger whatever we want to trigger after the dialog is complete.

**Comment by harshad1** [comment] 2024-04-21 04:02
Ok, the solution was simple. I have it included here - https://github.com/gsantner/markor/pull/2275/files

**Comment by gsantner** [comment] 2024-05-20 20:43
closed by #2277

**Closed** 2024-05-20 20:43 UTC
