### ISSUE TITLE
Google Pixel slow I/O

### ISSUE THREAD

**Issue by volt4ire** [gsantner/markor#1176] opened 2020-12-29 13:41 UTC
#### General information

* **App version:** 2.5.0
* **System:**  11 (fully-patched Pixel 4)

#### Description
Whenever I load the default folder in Markor's Files tab, (which I have set to a subfolder in my /Documents directory) it takes an extremely long time to load, and only shows the ¯\_(ツ)_/¯ shrugging emoticon. Sometimes it won't load at all if I leave the screen on the Files tab, and have to switch to a different tab like More or QuickNote before coming back to Files for the files in my default Notebook to be loaded. Other times even if it is fully loaded with the list of my notes, the Files tab will randomly switch back to the ¯\_(ツ)_/¯ shrugging emoticon. Is there a way to speedup the process, for example by caching its previous state, or is this slow loading a bug specific to my installation of Markor? Thanks!

**Comment by gsantner** [comment] 2020-12-29 14:18
Sounds like duplicate of #1120 . Not sure whats up with Google Pixel devices, but do they intentionally slow down disk I/O, or is it just bad hardware? lol

**Closed by gsantner** 2020-12-29 14:18 UTC

**Comment by gsantner** [comment] 2021-09-09 01:02
#1120
