### ISSUE TITLE
App crash when click double on enter button in app tools

### ISSUE THREAD

**Issue by iamank1t** [gsantner/markor#206] opened 2018-03-29 19:57 UTC
#### Expected behavior
While writing a quick note in app. If i click on enter button in editor tools, then app needs to take my text cursor to next line.

#### Actual behavior
When writing a quick note, i had to start my not from line so i press enter button which is provided in a bottom with other tools. When i press the enter button first time the text cursor goes to next line but when i press enter button again the app got crashed.

#### How to reproduce
To reproduce the bug follow the following steps :-
Note :- For better understanding of steps please watch bug recording.

- Open the app and go to quick note tab.
- Now write a word in editor and then find the enter symbol like this ↵ in the tools which are at top of your keyboard in a bar.
- Now press this "↵ button" twice and you see app got crashed. 

<pre><code>
* Device:  Samsung J7 Prime
* Operating system: Android 7.0 Nougatt
* App Version: v0.3.4
</code></pre>

#### Recording Of The Bug
https://www.youtube.com/watch?v=wBpyT0mCMZo
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@iamankit/app-crash-when-click-double-on-enter-button-in-app-tools">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by gsantner** [comment] 2018-04-08 19:06
I tried to reproduce the problem, but cannot reproduce it. Maybe it was fixed by something unknowingly.

**Closed by gsantner** 2018-04-08 19:06 UTC
