### ISSUE TITLE
v2.8.1 update: Saving issues

### ISSUE THREAD

**Issue by maksim-moskovko** [gsantner/markor#1470] opened 2021-10-14 05:59 UTC
## General information
* App version: 2.8.1 (f-droid)
* Android version: 11
* Device: POCO X3pro
* I understand that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

### Description

Markor autosave doesn't work, when my note open and then I switch to another app (e.g. Firefox). Manual saving before switching doesn't help the same way
Upd: it's save but text disappear. I must close note, and open it again to see text I write

**Comment by maksim-moskovko** [comment] 2021-10-14 06:14
> My daily device is poco-x3 Android 11, no problems. What is the OS/ROM you use?

I use MIUI by Xiaomi.eu 12.5.4. Markor 2.8.0 doesn't have this problem. Here's [video of a bug](https://youtu.be/uPjpWlESy6g)

**Comment by whichfinder** [comment] 2021-10-16 07:02
Hello
Facing the same issue: after editing note and switching to another app and back, added content disappear

**Comment by gsantner** [comment] 2021-10-16 09:55
Hm, I didn't spot any saving or file write related change from 2.8.0->2.8.1

**Comment by whichfinder** [comment] 2021-10-17 10:38
@gsantner I don't think it's autosave or save. I see that after switching between the apps, last lines are being removed from note file anlynd o from the bottom of file

**Comment by whichfinder** [comment] 2021-10-17 10:56
One more finding: if you add text -> save -> switch to another app -> switch back to markor note => last added lines are removed. 
If you add text -> click back button (arrow on the top) -> open note again => everything is saved

**Comment by gsantner** [comment] 2021-10-17 12:27
Ok, details are important to get it fixed, as I cannot reproduce the issue here

**Comment by gsantner** [comment] 2021-10-17 17:57
what is thr location of your documents?

does resetting the app settings make it work again?

**Comment by whichfinder** [comment] 2021-10-17 18:31
Hi
I have no sd card. I use documents folder in phone drive. Resetting the app settings did nothing.

Issue is really unstable.
I created new note and everything is saved.
I edited old note and once it saves everything, after several attempts I lost some lines from the bottom of note.
Exactly the same behaviour as OP show in video

**Comment by harshad1** [comment] 2021-10-18 16:50
@whichfinder

Could you turn off any syncing you may have for your notes folder (syncthing, Foldersync etc) and see if you can still reproduce the issue?

Also, could you check if speed and size affects the results? i.e.
1. open a large document and save it. 
2. open it again, add a line, and switch to another app
3. switch back immediately and see if the new line is still there
4. Try #3 again, but wait 30s or so before switching back to markor.

**Comment by DarkRF** [comment] 2021-10-21 22:26
I am affected as well. Hard to reproduce.
for me, it is happening on an earlier created very long _big_ simple text file. Short, new files are not affected.
Copying the contents to a new txt file reproduce the issue.
 
Not all the characters disappear, sometimes one or two remains. Thanks for the hint above, undo recovers the disappeared edits. (something unwanted happening when switching from the program.)
Uninstall and reinstall - same issue.

loose notes: 
- sometimes, new files open in view only mode.
- Setting to open the file on the end is totally ignored. (I got CTS testing this issue)
-Sorry to say, but the last release (f-droid) is a mess.
Anyhow, keep up, this is a great app.

**Comment by gsantner** [comment] 2021-10-21 22:59
I'm still curious why it started happening at 2.8.1 release, but not for 2.8.0. When checking the changes <https://github.com/gsantner/markor/compare/v2.8.0...v2.8.1> there is not really something related different.

**Comment by riveravaldez** [comment] 2021-10-30 18:03
Hi, sorry for the delay.

Issue seems fixed in Mordor, but one aspect of it was that changes in the text dissapeared when rotating the view/device, and in this case also the undo/redo history was lost. Now in Mordor you can rotate the view without loosing text/changes, but the undo/redo history still gets lost/deleted.
Probably different bug, but informing just in case.

Kind regards!

**Closed** 2021-11-01 22:23 UTC
Labels: bug

**Comment by gsantner** [comment] 2021-11-04 17:38
thanks for testing

#1482 #1483
