### ISSUE TITLE
Markdown: nvAlt (Notational Velocity) compatibility (settings option enter=double space end)

### ISSUE THREAD

**Issue by oztourer** [gsantner/markor#810] opened 2019-12-29 23:39 UTC
#### General information

* **App version: v2.2.3** 
* **Android:** 

#### Description

Just installed as a companion to nvAlt on my Mac, and it looks really promising. One small 'issue': nvAlt generates a line break on pressing Return. The Markor _editor_ shows separate lines on pressing Return but concatenates them in _view mode_. I know that two spaces at the end of a line generates a line break, but any chance of a settings option to generate breaks on pressing Return in the editor? Otherwise, this is an awesome app, thanks for all your efforts.

**Comment by gsantner** [comment] 2019-12-30 08:18
I have to think about it. In generally every other editor I used so far does really just what the button is - enter, and no additional magic.

**Comment by gamato** [comment] 2020-01-20 21:58
Hi. Maybe it could be done in a different way -- a new option in settings to break lines on single EOL in View mode. I have many markdown files where just single EOL separates some/many lines and other editors (can) show them not concatenated. If a line ends with double EOL, than the usual behaviour is used (no extra empty lines are inserted). This simple option would make Markor usable in many more scenarios. Thanks.

**Comment by oztourer** [comment] 2020-01-20 22:07
I think that gsanter's suggestion of a settings option to generate double spaces on pressing enter is the right solution for my use case and would show the files correctly back in NV.

**Comment by gamato** [comment] 2020-01-21 22:01
OK, then I guess I should create a separate feature request.

**Comment by gsantner** [comment] 2020-05-02 15:12
Closing as duplicate of #835 . Instead of insert "double space end", it's rather to treat newline a a line break.

**Closed by gsantner** 2020-05-02 15:12 UTC
Labels: wait/maybe/upstream
