### ISSUE TITLE
button to previous page

### ISSUE THREAD

**Issue by pussstudio** [gsantner/markor#2017] opened 2023-04-09 04:21 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **enhancement/feature request**. Not a [bug or question](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The wanted feature/enhancement is not present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor's settings are not touched. If your desired feature is present, you don't need to open this issue. The change will be part of the next Markor update.)

### Description

1. when i click linked word in md file, page moves from A page to B page.

in B page, because i want to go to previous page which is A page, i push the back button of the cellularphone.
then, the page is not moving to previous page. instead, going to the folder list. 
i want to additional button to go to the previous page.

2. 
3. 

### Information

Android version: 
Device: 
App Version: 

### Source

Google Play

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment] 2023-04-16 11:55
More or less this is a duplicate of whats wanted at #705

**Closed** 2023-04-16 11:56 UTC
Labels: invalid/duplicate/upstream
