### ISSUE TITLE
Cannot type after creating new note

### ISSUE THREAD

**Issue by mbomb007** [gsantner/markor#1771] opened 2022-07-22 11:23 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

After creating and naming a file, it opens and has a cursor. If I tap to type the android keyboard shows only briefly then disappears. I have to back out of the file, then re-edit in order to type.

### Steps to reproduce

1. Create a note
2. Give it a file name
3. Tap to edit, the android keyboard shows
4. Tap on the keyboard (e.g. a letter or the clipboard button) 
5. The keyboard disappears without anything being typed. 
6. Exit file with back button
7. Open note from list and then can edit and save successfully

### Information

Android version: 8.1.0
Device: samsung galaxy j327v
App Version: 2.10.0

This has been happening for a couple weeks at least, but is a more recent issue, not before the last few versions for sure.

### Source

F-Droid

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment] 2022-07-22 16:33
Cannot reproduce, tried multiple times. Android 11, aosp keyboard.

Since you say "last few versions&weeks", well there are not so often new versions. So might also started happening without a update of Markor, so yesterday version X worked, today X does not.  
Maybe related to your keyboard software?

**Comment by gsantner** [comment] 2022-08-06 12:13
Closing as unreproducible, didn't hear from anybody else, and I myself use Markor every day  - never run into this.

**Closed by gsantner** 2022-08-06 12:13 UTC
