### ISSUE TITLE
Constant Crash when opening a file from a folder on SD card 

### ISSUE THREAD

**Issue by aleksfadini** [gsantner/markor#732] opened 2019-10-10 21:35 UTC
#### General information

* **App version:** 2.1.4 f-droid
* **System:** latest Android 9 (Galaxy note 10 plus)

#### Description
When opening any .md file from a folder on my SD 
Markor crashes.

#### Log
Will provide as soon as I figure out how

[crash.tar.gz](https://github.com/gsantner/markor/files/3714765/crash.tar.gz)

**Comment by gsantner** [comment] 2019-10-10 22:36
Thanks for comment and also video. I tried it on my phone right now (too latest Android 9 and SD card).

To create debug logs, see my guide <https://gsantner.net/blog/2018/03/19/android-contribution-guide.html?packageid=net.gsantner.markor&project=markor&web=https://github.com/gsantner/markor#logcat>. If you have a computer with linux (which I assume because you use jekyll + termux :D ), pidcat is your best option.

Please don't uninstall, update or reinstall the app if possible to make sure you can still reproduce the issue and report right log

**Comment by aleksfadini** [comment] 2019-10-11 00:13
Thank you for the hint about pidcat (good assumption, and yes jekyll!). Sorry about the duplicate, indeed it might be a duplicate, I searched and somehow missed #603 .

Markor is great and your support is awesome also. Will get back to you with logs, soon.

**Comment by gsantner** [comment] 2019-10-21 23:09
I'm closing this as a potential duplicate of #603. Please add a log there when you have it.

**Closed by gsantner** 2019-10-21 23:09 UTC
Labels: q/discussion/feedback
