### ISSUE TITLE
Error: Could not open file / File permission granting issue

### ISSUE THREAD

**Issue by opusforlife2** [gsantner/markor#1886] opened 2022-10-08 19:53 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

If you manually remove the files permission for Markor and then try to open it, the system shows a toast saying "Error: Could not open file."

Then, if you grant the permission again, Markor works normally.

This doesn't occur when the app is opened after the first install. It correctly asks for permission then. Which means revocation of the permission is a scenario that needs to be handled separately.

### Steps to reproduce

1. Manually revoke files permission for Markor.
2. Try opening Markor.
3. System toast appears saying can't open.

### Information

Android version: 12 (LOS 19.1)
App Version: 2.10.5

### Source

F-Droid

### Format / File type

Not specific

**Comment by gsantner** [comment] 2022-10-08 20:01
> 2. Don't use Markor for a few days (no idea how many).

Thats rather hard to reproduce^^.


But what sure would be helpful is if you can post a log related to the crash when you run into this again.

**Comment by opusforlife2** [comment] 2022-10-09 12:43
Okay, I don't know why I didn't think of this before. I just tried manually revoking the permission and got the same results. It's fully reproducible.

And I paid closer attention this time. I can't say for certain that there is a crash. I don't get that standard dialogue saying the app has crashed.

Instead, I get a toast with the system app icon (that white android on a green background) saying "Error: Could not open."

Restoring the permission lets Markor open again, like normal. No side effects of this behaviour are apparent.

**Comment by gsantner** [comment] 2022-10-16 09:30
@opusforlife2   
How do you **remove** the permission grant **manually**? I don't see any storage related permission or anyting at all. But app has asked before and can access just fine.

[screenrecord-2022-10-16_11.28.07.webm](https://user-images.githubusercontent.com/6735650/196028268-d7fefdb7-348b-49b0-9325-cf236383b2de.webm)

**Comment by gsantner** [comment] 2022-10-16 09:47
> This doesn't occur when the app is opened after the first install. It correctly asks for permission then. Which means revocation of the permission is a scenario that needs to be handled separately.

The file access is mostly guarded by `if (!permissionGranted -> dialog)`, not sure.

> Try opening Markor.
> System toast appears saying can't open.

Can you please attach a android log (`adb logcat`)? This is what I miss most here, I don't know where it crashes.

I also checked Google Play which usually has something over-the-top in terms of numbers if there is something really urgent and affecting most people. This is not the case here, so I don't know looks like a device specific problem?!

![Bildschirmfoto_2022-10-16_11-45-17](https://user-images.githubusercontent.com/6735650/196028822-55e7d964-1b97-411c-a413-3c3161278f7e.png)

**Comment by opusforlife2** [comment] 2022-10-16 19:57
![Markor](https://user-images.githubusercontent.com/53176348/196055332-4d9dda90-c261-4d65-9182-8aeb54c28e64.png)

This is the permission I see, along with the Microphone permission in your video. Is there no feature of Markor that needs this permission?

**Comment by gsantner** [comment] 2022-10-16 20:19
I dont see any file permission in settings in android 12. and yes it needs it.

microphone is only needed for voice notes, not required anywhere else.

**Comment by opusforlife2** [comment] 2022-10-17 18:20
> I dont see any file permission in settings in android 12

I can only speculate here: Google was allowing full storage access to apps only on a case-by-case basis, last I heard. Since LOS can function without the Play Store, it seems to have surfaced the permission for the user to freely modify.

**Comment by gsantner** [comment] 2022-11-05 03:00
> I can only speculate here: Google was allowing full storage access to apps only on a case-by-case basis, last I heard

This is correct. And Markor has this permission granted.

**Comment by gsantner** [comment] 2022-11-05 03:02
So...I don't know, I use Markor every day and tried a few different Android emulator versions after a while of past use again... And I had zero cases where something got revoked not asked again properly, or crashing related to that.

So as I can't reproduce anything here, I'm not sure how I could help you here.

**Comment by opusforlife2** [comment] 2022-11-05 08:31
Do you have any way to try an LOS ROM or another that surfaces this permission? That seems to be the only way to test, since it's likely only custom ROMs will have this permission visible. I don't think any OEM will 'deign' to allow users to mess with this.

**Comment by gsantner** [comment] 2022-11-05 09:44
I run LOS 18 as daily driver, no issue there

**Comment by opusforlife2** [comment] 2022-11-05 11:14
And you don't have this permission visible? That's strange. I thought it was added in Android 11, and so LOS 18.

**Comment by gsantner** [comment] 2022-11-05 11:25
Sure? It is MANAGE_EXTERNAL_STORAGE, it is also visible fine on my LOS device (though not on emulator somehow).

**Comment by opusforlife2** [comment] 2022-11-05 11:30
Oh, my bad. Are you saying that toggling off the All Files permission from Markor's App Info and then opening Markor works fine for you?

**Comment by gsantner** [comment] 2022-11-05 11:39
Yes, thats what I'm trying to say to all these kinds of issues - it works just fine. And if the permission went away, Markor just asks again - which you can see in the video that it does. And then when I granted it, file browser reloads and all files are visible. This is exactly the scenario the code I wrote to behave this away - as expected. Don't know what special thing you are running into there.

![screenrecord-2022-11-05_12 35 56](https://user-images.githubusercontent.com/6735650/200118011-c5bca6bd-794c-47fb-add5-1bbfa1ce1585.gif)

**Comment by opusforlife2** [comment] 2022-11-05 11:43
ADB logs it is! BRB.

---

But what were your initial comments about, then, where you stated and even posted a video showing that this permission wasn't there? Your latest GIF has it.

**Comment by gsantner** [comment] 2022-11-05 11:46
>  (though not on emulator somehow).

As I said, I didn't see it on the emulator with other android/os images. Though still everything works/worked fine and I at last got once the popup for the permission. Never had a problem so far after accepting it once, and it surely appeared at last once.

**Comment by gsantner** [comment] 2022-11-05 11:47
Looks like I probably will close this as I can't really help you on something I absolutely can't reproduce anywhere.

**Comment by gsantner** [comment] 2022-11-05 11:48
So if you want this fixed, please go ahead, debug it on your device, find the issue, fix it and make a merge request. Thank you.   
Otherwise I close this, I can't help you on something I absolutely can't reproduce anywhere.

**Comment by opusforlife2** [comment] 2022-11-05 12:27
Wait I'm not a coder. The only relevant logs I see are:

`Permission to access file: /storage/emulated/0/Markor is denied`
followed by
`Writing to a non-default top level directory is not allowed!`

Is that helpful at all?

**Comment by gsantner** [comment] 2022-11-05 12:39
> Wait I'm not a coder

Yeah, still I can't help you here. So either we can help you to learn coding and you or somebody else reproducing it...looks into it... or I close it.

> Is that helpful at all?

No

**Comment by opusforlife2** [comment] 2022-11-05 12:49
Closing it is fine. Leaving it open for someone else is also fine. It's not a major issue. You've been surprisingly interactive about this, actually. It made me think that it _was_ a major issue and I was surely missing something. xD

**Comment by gsantner** [comment] 2022-11-05 13:18
No, when such a really rrally bad case happens where nothing works for anybody and all just crashes, no files can be opened at all.....  
I would get tons of personal private emails by angry people and loads of crashes on google play.    
And neither is the case here

**Comment by gsantner** [comment] 2022-12-20 08:08
Reopened as I get frequent feedback like this now - though still zero times reproduced here.

**Comment by harshad1** [comment] 2022-12-21 08:09
Settings > privacy > permission manager > Files > see more apps that can access all files > markor (or Mordor)

This is on stock android 13 (pixel 7)

Disable it and the crash is reproducible.

I'll look into getting a trace tomorrow

**Comment by gsantner** [comment] 2022-12-29 17:49
By now I get frequent reports, emails and comments about this crash.

**Comment by gsantner** [comment] 2022-12-29 17:51
By now I get frequent reports, emails and comments about this crash. So yes it's definitely very important to fix. Still unfortunately I couldn't reproduce this yet at any time - it always asks properly here. Both on my device, and also on Emulator with a different/newer Android version.

**Comment by indeedwatson** [comment] 2023-01-17 22:28
so this app has become unusable for me for this reason, there's no workarounds?

**Comment by harshad1** [comment] 2023-01-17 22:30
@indeedwatson `Settings > privacy > permission manager > Files > see more apps that can access all files > markor `

Give it permissions and it should work. I'll take another stab at debugging this over the coming weekend.

**Comment by harshad1** [comment] 2023-01-21 04:06
By my understanding, the fundamental issue is that markor launches a dialog to request file permission, but this dialog is not modal and so we continue to do things which require file permissions before they have been granted resulting in a crash.

What we need to do is detect permission status at onResume, kick out to a separate activity and restart the MainActivity after permissions have been granted.

**Comment by harshad1** [comment] 2023-01-21 04:50
It's not clear to me at all. I think it's different for debug builds

Jan 20, 2023 20:46:48 opusforlife2 ***@***.***>:

**Comment by gsantner** [comment] 2023-01-22 00:56
Hello everybody, if interested please help with testing a potential fix (#1957). test builds can be downloaded from [here](https://github.com/gsantner/markor/actions?query=branch%3Apermission_crash). Probably the top-most is of interest. The apk download can be downloaded on the detail page then on the bottom.

![grafik](https://user-images.githubusercontent.com/6735650/213895749-1141f35d-5a3a-4b6d-8b80-dee4c4bf934d.png)

**Comment by harshad1** [comment] 2023-01-27 05:29
@gsantner I think I have a way of addressing this, but we need to determine what to do if the user _does not_ grant the storage permission. 

Should we
- show a message and exit the app?
- change directory and Todo + qn file paths to app storage?
- something else?

**Comment by harshad1** [comment] 2023-01-28 07:28
@opusforlife2 could you test the version I just pushed up? It does not incorporate the yes / no logic you described. But should correctly request permissions when you launch markor.

@gsantner We have `doIfExtStoragePermissionGranted()` in many places. Is there any use for this if we basically force users to grant file permissions at the start?

If not, we could simplify a lot of code and just  request file permissions (exit if not granted) in the MarkorBaseActivity or some place.

**Comment by harshad1** [comment] 2023-01-28 16:55
We have `doIfExtStoragePermissionGranted`

```java
                case R.string.pref_key__share_into__create_document: {
                    if (permc.doIfExtStoragePermissionGranted()) {
                        createNewDocument();
                    }
                    return true;
                }
                case R.string.pref_key__favourite_files:
                case R.string.pref_key__popular_documents:
                case R.string.pref_key__recent_documents:
                case R.string.pref_key__share_into__existing_document: {
                    if (permc.doIfExtStoragePermissionGranted()) {
                        showAppendDialog(keyId);
                    }
                    return true;
                }
```

Everywhere

Technically this is good as it allows some features of markor to be used without permissions. Looking into if / how we can make this cleaner.

**Comment by gsantner** [comment] 2023-01-28 17:36
I will try to answer and check out all the comments and ideas on the weekend.

**Comment by harshad1** [comment] 2023-01-28 18:39
The latest version of this includes some starting attempts to make the all files permission more granular. i.e. only request if the user attempts to access a folder which requires permissions. Its still a work in progress and a lot of edge cases need to be handled.

**Comment by gsantner** [comment] 2023-01-28 22:22
> Then maybe release the initial quick fix in the upcoming version

I'm cautious with that. Even if it's bad, it's better the application doesn't start at all, then it empties some file unwanted

**Comment by k3b** [comment] 2023-02-18 13:14
On my Android-10 the permission problem is reproducable as described in closed #1964
 after a fresh install (Text copied from closed #1982) :

Steps to reproduce

    Using debug version Mordor instead of Markor
    uninstall Mordor
    In Filemanager make shure that folder /storage/emulated/0/Documents/mordor/ does not exist (delete or rename)
    In Androidstudio put a breakpoint at DocumentEditAndViewFragment.isStateBad()
    install and debug Mordor
    => isStateBad fails with testCreateParent /storage/emulated/0/Documents/mordor/todo.txt
    => isStateBad fails with testCreateParent /storage/emulated/0/Documents/mordor/QuickNote.md
    => App crashes with "android.view.WindowLeaked: Activity net.gsantner.markor.activity.MainActivity has leaked window ..."

**Closed** 2023-02-26 10:56 UTC
Labels: q/discussion/feedback

**Comment by gsantner** [comment] 2023-02-26 12:01
Hello everybody,

please download and test the development version from [here](https://github.com/gsantner/markor/actions/runs/4274644289#artifacts) (click apk button). Does file management work now and the crash is gone?

**Comment by k3b** [comment] 2023-02-27 15:27
@gsantner 

> Does file management work now and the crash is gone?

On my lg android-10 it now works as expected after a fresh install 👍

**Comment by gsantner** [comment] 2023-03-20 18:52
Markor v2.10.8 was tagged today. Update from here <https://github.com/gsantner/markor/releases/tag/v2.10.8>. F-Droid builds the updated probably before the weekend.
