### ISSUE TITLE
In a list, current item merges with next item when using auto complete

### ISSUE THREAD

**Issue by rrittwikc** [gsantner/markor#1875] opened 2022-10-04 06:54 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [ ] The bug is not present in the latest code version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

**What problem did you encounter**

Suppose an unordered list has two items
- a
- b

Now I move the cursor to the end of first item and press enter. A new empty list will be inserted between a and b. Now if you use any auto completion in this new list item, then the item "- b" will merge to the new list item.

**What did you expect to happen**

The new list item should not merge to the next item.

### Steps to reproduce

1. Create and open any markdown file viz. test.md
2. Type "- a" (without quotes) and press enter
3. Type "b" (without quotes) and press enter
4. You now have an unordered list of two items.
5. Go to the end of first list item (i.e. - a) and press enter
6. In the new empty item insert any text from auto completion

### Information

Android version: 12
Device: Samsumg Galaxy M12
App Version: 2.10.4 (140)

### Source

Google Play

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment] 2022-10-04 07:03
Do you mind to attach a short screenrecord showing it, just to be sure?

**Comment by rrittwikc** [comment] 2022-10-04 07:12
Frist I create two list items a and b

![1](https://user-images.githubusercontent.com/5364238/193756828-15229864-c422-43b5-ab9f-367a70a8d98e.jpg)

Then I move to end of first item and press enter to create a new empty item.
Note that in auto completion the first one is "long".

![2](https://user-images.githubusercontent.com/5364238/193756834-f0c796e8-8e02-459b-9abc-93d39f0ee3c3.jpg)

If I press than auto completion (i.e. long) I get the merged items

![3](https://user-images.githubusercontent.com/5364238/193756837-89fb2309-958e-4be4-972e-dca5308bd9eb.jpg)

**Comment by rrittwikc** [comment] 2022-10-04 07:20
https://user-images.githubusercontent.com/5364238/193758502-b7291bf2-3aa6-47d5-ae75-25e11d493767.mp4

**Comment by harshad1** [comment] 2022-10-05 17:38
This is strange. I remember explicitly addressing this over a year ago. I cannot reproduce this on my Pixel 3 (Android 11).

Could you test this with different keyboards?

**Comment by rrittwikc** [comment] 2022-10-06 05:24
@harshad1 You are right. This is happening only in Samsung keyboard. I just install google keyboard and gboard works fine. So I think this is the problem of Samsung keyboard only.

**Comment by gsantner** [comment] 2022-11-05 12:27
Closing, seemingly not really a bug in Markor behaviour.

**Closed by gsantner** 2022-11-05 12:27 UTC
Labels: wait/maybe/upstream
