### ISSUE TITLE
When sharing from another app, would be nice to add a title

### ISSUE THREAD

**Issue by arteteco** [gsantner/markor#427] opened 2018-11-11 11:49 UTC
Hello everyone,
I'm looking for a simple, foss bookmark manager since a while and markor looks awesome. Very easy to put links in categories by just choosing a different file.

When I share a link, though, it may be really nice to add a title to it.

For example, if I share `github.com`, I'd love to be able to choose a title like `Github`  and have it formatted like this automatically
`[Github](github.com)`

That would be great.

Thanks!

**Comment by gsantner** [comment] 2018-11-11 11:51
the problem is that some browsers share the title with the TEXT data automatically, while others don't. There is no unified solution available due every behaves differently.

**Comment by arteteco** [comment] 2018-11-11 16:45
thanks @gsantner . What if we let the browser prefill the field and in case of need we edit it, like it is in most web browsers? Would that be possible?

**Comment by gsantner** [comment] 2018-11-11 17:03
You cannot decide this. That is on developers of browsers.

Still you can freely edit the textbox in the import screen before pressing import.

**Comment by gsantner** [comment] 2018-11-13 15:54
the text= can be also from your url. No therese currently no common way to retrieve the information needed. And doing requests for URLs is not a goal.

**Comment by SmilingHorse** [comment] 2018-12-12 20:24
@gsantner it's possible to pass the title and url separately with a share intent. See how sharemarks does it here: https://github.com/appham/Sharemarks/blob/master/app/src/main/java/com/appham/sharemarks/view/MarksActivity.kt

**Comment by SmilingHorse** [comment] 2018-12-13 14:33
Here's fennec and the built-in android browser:
https://gist.github.com/SmilingHorse/79fe6c31467f5a1c6c6a9244e88bc793

**Comment by gsantner** [comment] 2018-12-13 14:43
@SmilingHorse thanks, welcome

There you go, what I meant with my previous comments. Your builtin browser does not share the subject e.g.

**Comment by SmilingHorse** [comment] 2018-12-13 16:16
Yeah looks like Mozilla expanded the use of the email intents.

https://developer.android.com/guide/components/intents-common#Browser

https://developer.android.com/guide/components/intents-common#Email

But intents are still the solution: Just write a webextension for chrome (and I guess firefox too nowadays) that will pass an intent to Markor. More on that here: https://developer.chrome.com/multidevice/android/intents

**Comment by gsantner** [comment] 2018-12-15 17:21
@SmilingHorse : On mobile you cannot extend chrome with plugins, you could never do that ever. Only on desktop. And what you noted is about something completly different, links in webbrowser itself with contents in URL (so every URL in the world would need to adapt - which won't happen).

**Comment by gsantner** [comment] 2018-12-16 18:57
Yeah, Firefox support them, and I use that too.
But as you already see, that's all not straight forward and rather complex. Additional browser addons are out of scope for the Markor project, hope you can understand that :smile: . Even more, as you can't do it for majority of mobile browsers anyway..^^

**Comment by SmilingHorse** [comment] 2018-12-16 21:41
Oh well at least I tried :) Thanks for considering it at least.

**Closed** 2018-12-23 17:54 UTC
Labels: wait/maybe/upstream

**Comment by gsantner** [comment] 2018-12-23 18:00
Hey everybody, theres some news on this.

Links are now automatically shown at import in markdown manner and title is prepended if available. This requires that the browser supplies both URL + title. As this is not mandatory for browsers to provide (and many in fact do not) the data this will not work with all browsers, but should work with most commons ones.
Please don't ask to support `browser X`, if they provide data as they should they do, if don't then not - ask at theirs bug tracker if required. Markor can't fix other apps lacking intents.
