### ISSUE TITLE
Broken unittests in branch "master" at net.gsantner.markor.format.wikitext.WikitextLinkResolverTests

### ISSUE THREAD

**Issue by k3b** [gsantner/markor#2127] opened 2023-10-12 18:21 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

On 2023-10-12 20:15 i cloned current "master" branch and realized that some unittests at net.gsantner.markor.format.wikitext.WikitextLinkResolverTests failed

### Steps to reproduce

1. Checkout branch "master"
2. In AndroidStudio under "app/app/java/net.gsanter (test)" in Contextmenu execute "Run Tests in ..."

### Information

using Android Studio Giraffe | 2022.3.1 Patch 1
Build #AI-223.8836.35.2231.10671973, built on August 17, 2023
Runtime version: 17.0.6+0-b2043.56-10027231 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    plantuml-parser (0.0.5)
    PlantUML integration (6.0.0-IJ2022.2)
    com.github.shiraji.emoji (3.1.0)
    org.intellij.RegexpTester (1.0.8)
    net.seesharpsoft.intellij.plugins.csv (3.2.1-223)
    com.github.shiraji.yaemoji (1.0.7)
    com.mallowigi.colorHighlighter (14.1.0)
    com.haulmont.jpab (2023.3.5-223)

### Source

git master branch

### Format / File type

Something else (-> Additional info)

**Comment by k3b** [comment] 2023-10-12 18:27
![grafik](https://github.com/gsantner/markor/assets/1374583/b5336fcd-0c2d-43bd-b70d-6e081fc1c16a)

**Comment by gsantner** [comment] 2023-12-03 13:31
There seems to be nobody active working on WikiText/Zim currently, unfortunatley.

**Comment by halfdane** [comment] 2024-01-11 15:10
I tried to reproduce with the given steps, but the tests are green.

Might be a windows issue, or related to the version of Android Studio (I'm using `Hedgehog`, not `Giraffe`

# Information

Android Studio Hedgehog | 2023.1.1 Patch 1
Build #AI-231.9392.1.2311.11255304, built on December 26, 2023
Runtime version: 17.0.7+0-17.0.7b1000.6-10550314 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-14-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    debugger.new.tool.window.layout=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.experimental.ui=true

Non-Bundled Plugins:
    name.kropp.intellij.makefile (231.8109.91)

Current Desktop: KDE

**Comment by gsantner** [comment] 2024-01-11 18:26
I tried it back then and they were failing also in command line `make test`. They pass now however.

So, closing. @k3b can you confirm that it passes on master for you too?

**Closed by gsantner** 2024-01-11 18:26 UTC
