### ISSUE TITLE
Trying to add a special key while using quicknote causes a crash

### ISSUE THREAD

**Issue by jyjsunny** [gsantner/markor#1700] opened 2022-05-11 09:09 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

Trying to add a special key while using quicknote causes a crash

There is a video:

https://user-images.githubusercontent.com/92309998/167813386-2e8252db-4ffc-4ce7-8378-35729034baa0.mov

### Steps to reproduce

1. click to use the "quitenote"
2. input some words
3. click to add a special key
4. click to "ok"
5. crash and exit

### Information

Android version: Android 8
Device: Google Pixel 4
App Version: 2.8.6

### Source

Google Play

### Format / File type

No

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment] 2022-05-11 17:37
I can reproduce this. Will investigate and fix.

**Comment by gsantner** [comment] 2022-05-21 11:16
Duplicate of #1699 . What did you expect to happen when clicking OK? You didn't select something!

See my comment in 1699.

**Closed by gsantner** 2022-05-21 11:16 UTC
