### ISSUE TITLE
zim: links within a page to a heading/object result in NullPointer exception

### ISSUE THREAD

**Issue by Ra-su** [gsantner/markor#1882] opened 2022-10-06 17:57 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is not present in the latest code version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

A zim document containing a page internal link (starting with '#', resolves to a header or link) creates an exception in view mode:
`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.equals(java.lang.Object)' on a null object reference`

Minimal example: [Markor_Zim_Pagelinks.txt](https://github.com/gsantner/markor/files/9727237/Markor_Zim_Pagelinks.txt)

The `[[#42]]` creates a link to the header `== 42 ==`

### Steps to reproduce

Open a zim page with a page-internal link. A minimal example is attached in the description.

### Information

Android version: 8.1
Device: Moto G5 Plus
App Version: v2.10.5 (141)

### Source

Google Play

### Format / File type

Wikitext, Zim

### Additional info / Log

```shell
-
```

**Comment by fredericjacob** [comment] 2022-10-06 22:26
Don't worry, I did not forget about Markor, I have my personal backlog for development waiting for me. It was just not a priority in the last months because of multiple large hobby projects, but I will certainly return (soon). :)

**Comment by gsantner** [comment] 2022-10-06 22:56
hehe, long time no hear. Hope you are well! 😄

**Comment by fredericjacob** [comment] 2022-10-06 23:08
Thanks, yes I am. 😊
Looking forward to diving in again. Still, more Zim contributors would be nice of course!

**Comment by gsantner** [comment] 2022-10-06 23:11
Btw what might be new to you, Zim is now wikitext at Markor. As there are many wikitext-ish syntax out there, and Zim happens to be one of them for the much biggest part.

**Comment by fredericjacob** [comment] 2022-12-04 01:47
@Ra-su I could not reproduce the issue - are you still experiencing it with the most recent version of Markor?
I tried your sample file - I can switch to view mode without an exception:
![grafik](https://user-images.githubusercontent.com/45181277/205469770-5911f7ce-0889-459f-8712-84fba37c37b7.png)
If I click the link, I get this popup, but no exception as well:
![grafik](https://user-images.githubusercontent.com/45181277/205469785-10139077-affa-40dc-ae50-ef154f59ca2d.png)

By the way: Zim links with page name + a reference, e.g. "[[+MyPage#some-anchor]]", don't work yet with Markor, but I'm currently working on making these compatible (for now just ignoring the anchor part of the link).

**Comment by Ra-su** [comment] 2022-12-04 11:59
Yes (v2.10.6 (142), from Google Play Store as well as F-Droid).
Neither cache deleting, nor deleting of user data, nor complete re-installation (from 2 different sources) showed any difference.
Edit mode is OK, but view mode will raise an exception.

Any ideas how I can support debugging? Does Markor create a log file? I couldn't find anything in the settings.

**Comment by Ra-su** [comment] 2022-12-04 12:04
Just found #1895, which answers my question regarding logging and debug support, I guess :-)

**Comment by fredericjacob** [comment] 2022-12-04 12:42
Hmm could you try the following and report if something changed for each of the cases?
1. Remove the link and try to open view mode (should work)
2. Use a link with some text instead of numbers (e.g. "[[#my-anchor]]")
3. Instead use a valid link to some page, e.g. "[[+Subpage]]"
4. Instead use as page link including an inner page reference, e.g. "[[+Subpage#my-anchor]]"

**Comment by Ra-su** [comment] 2022-12-04 13:17
1. Works
2. Raises exception (I used: heading text `== My Heading ==`), link `[[#my-heading]]`)
3. Works as expected (no exception in view mode, tapping on the link opens the other page)
4. Mixed results here: no exception in view mode, but by tapping on the link a new page/document is created with the file name `Subpage#my-anchor.txt` (from burger menu > Info > Name, the location is correct (in the subdirectory with the name of my test page)) instead of opening the existing file `Subpage.txt`

**Comment by fredericjacob** [comment] 2022-12-04 19:36
Ah, I think I found the reason for the bug - finally I could reproduce it. :)

First problem which I encountered: Inner page links like "[[#my-heading]]" are considered as relative links.

Second problem (the actual one which leads to the exception): Relative links are resolved by traversing up the folder hierarchy, starting from the current page, and checking if an according subpage exists from any point in the hierarchy. If a relative link cannot be resolved because no accordingly-named subpage exists from any parent folder AND the zim notebook root directory is not reached at some point, there is no point to stop for traversing and finally the "current page" becomes "null" (as soon as the root of the filesystem is reached), which leads to an exception.

Long story short - those two facts should apply to you, @Ra-su . Can you confirm those?
1.  If you replace the inner page link "[[#42]]" with any other invalid (non-existing) relative link like e.g. "[[Invalid page]]", the same exception occurs when trying to enter view mode.
2. Your "Notebook" location is set incorrectly and your test page is not part of this notebook - i.e. you cannot reach the notebook root location at any point by just traversing through all parent folders of your page.

I will fix the treatment as inner page links as "relative links", as well as making the traversal logic more robust, so that even wrongly set notebook dirs do not cause errors in rendering view mode.

@Ra-su If you use multiple zim notebooks or just want to keep your current setting for the Notebook location in Markor, consider checking the option "Dynamic search for notebook root" - this way, Markor will search for the folder with the "*.zim" file and use this as notebook root.

**Comment by Ra-su** [comment] 2022-12-04 22:50
@fredericjacob My Zim notebook is located under /Notes (it contains the '.zim' sub-directory), while the Markor directory is under /Documents/markor. If I put the Zim file with the relative link into /Documents/markor, I can view it without getting an exception. If I tap on the link, I get the same message as in your screenshots in https://github.com/gsantner/markor/issues/1882#issuecomment-1336298067
The same file in my /Notes Zim-directory raises an exception in view mode. From your explanation, I guess this would meet your expectation?
With the enabled "Dynamic search for notebook root" option, there is no exception -- again, this would meet your expectation, right?
May I comment that this option is a little bit obscure for the clueless user? There might be a program-internal reason, why this option exists, but from the user´s point of view, it should "just work".
Anyway, thank you for your support and advise.

**Comment by fredericjacob** [comment] 2022-12-05 01:35
Yes this is what I expected. The error occurred because the /Documents/markor directory is not a parent directory of the /Notes directory, so there was no "stop folder" for the search. With the additional setting the folder with the .zim file is automatically recognized.
My recent pull request fixes the issue in the sense that there won't be an exception any more.

Yes, of course you may comment about that - it's always good to get feedback about usability. So maybe it makes sense to communicate the functionality better in some way, or use different defaults in the future, to make it less obscure.

**Closed** 2022-12-08 23:20 UTC
Labels: bug
