### ISSUE TITLE
Crash after intro tour on Chromebook

### ISSUE THREAD

**Issue by ceccadroid** [gsantner/markor#1907] opened 2022-10-27 07:28 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Mordor**. Don't worry; Markor and Mordor appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Installed on Chromebook (both from F-droid and frm Play Store) but close after the tutorial.
No way to open it again, also after delteing cache and data

### Steps to reproduce

1. Install on Chromebook
2. Launch and see the tutorial
3. Crash

### Information

Android version: Cromebook OS
Device: Chromebook
App Version: latest from F-droid and Play Store

### Source

Something else (-> Additional info)

### Format / File type

Something else (-> Additional info)

### Additional info / Log

```shell
- tried both F-droid and Play Store.
- from F-droid installation via adb.
- impossible to create/modify any type odf file due to crash after tutorial.
```

**Comment by gsantner** [comment] 2022-10-27 07:47
I don't own a chromebook so needs somebody else to check. If you know how to, a merge request to fix it is welcome.

Otherwise, can you add a error log? (adb logcat)

**Comment by gsantner** [comment] 2022-11-05 02:58
Can you please attach a crash log? Thank you!  
Otherwise I will close the bug.

**Comment by gsantner** [comment] 2022-11-05 03:08
@orez-ero (chromebook user from #1877 )
Can you reproduce this bug?

**Comment by renedupont** [comment] 2022-11-13 00:01
Hello @gsantner
Not sure if its the same root cause since I am on a samsung mobile phone running Android 8.0.0 but at least I have the same issue. It crashes at the end of the intro when pressing 'finish' and an info appears: `Error: Could not open file.` Reopening causes to show that error straight away without the tour.

I attached my logcat output as txt file from running it via android studio on my phone. I guess line 631 is of most interest? I terminated the process in the end.
[logcat.txt](https://github.com/gsantner/markor/files/9996255/logcat.txt)

**Comment by gmccullo** [comment] 2022-11-13 11:01
Is there any way to assign the Notebook location to a folder on the sdcard?

**Comment by ss11mik** [comment] 2022-12-08 07:44
Hello,
so I just experienced probably the same issue after installing on Android 7.1.2. with latest apk (v2.10.6). I managed to solve it by manually granting permission to storage in the settings. Issue  #1886 might be of a relevance.

**Comment by gsantner** [comment] 2022-12-08 09:59
then, please move your comment there

**Comment by ss11mik** [comment] 2022-12-13 13:17
The comment is not related that issue, I only found a solution (at least for me) to this issue there and thought it might help someone having this problem.

**Comment by gsantner** [comment] 2022-12-29 17:48
After reading this again, I assume it's duplicate to #1886 , so closing this one

**Closed by gsantner** 2022-12-29 17:48 UTC
Labels: good first issue, wait/maybe/cantreproduce, help wanted
