### ISSUE TITLE
Feature Request: enable choosing automatic RTL/LTR text direction in preview setting

### ISSUE THREAD

**Issue by doronbehar** [gsantner/markor#291] opened 2018-07-08 04:47 UTC
Settings has a boolean option under preview section for RTL rendering. I think  there should be an option for `dir=auto` option just like in HTML.
Most bilingual users which write in RTL languages such as Hebrew and Arabic write sometimes in English as well.

Thanks for a wonderful app BTW.

**Comment by gsantner** [comment] 2018-07-13 18:01
You can inject RTL or LTR via custom css option and take the other as default setting

**Comment by doronbehar** [comment] 2018-07-13 18:05
F-droid hasn't updated to 0.3.6 yet. I wouldn't have missed it otherwise.

Thanks anyway.

**Comment by gsantner** [comment] 2018-07-13 18:06
0.3.10 is the latest release and available on fdroid. 0.3.6 is old.

**Comment by doronbehar** [comment] 2018-07-13 18:16
Then where can I find the custom CSS option?

**Comment by gsantner** [comment] 2018-07-13 18:16
In Preview, Inject.

**Comment by doronbehar** [comment] 2018-07-13 19:46
From some reason F-Droid hasn't updated me to the latest version although it was available. I've injected this (for reference):
```html
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      document.body.setAttribute("dir", "auto")
    })
  </script>
```
Thanks again.

**Comment by OssNasr** [comment] 2019-01-06 22:55
Actually that script tag not working with me,

This works well :smile:
```<div style='direction:rtl;'> Arabic goes here </div>```
The problem is, not all people know about CSS to inject into document :(

**Thanks for the great App BTW :heart:**

**Comment by gsantner** [comment] 2019-01-06 23:11
@doronbehar 
I also tried your posted javascript, but this seems to not adapt on a per-line basis but on the whole document. So at least no help for #478 , but still a good hint!

@OssNasr You're welcome! Yeah the mentioned line is exactly what I meant with `per-line basis`, this can be done for html this way of course! :smile:

**Comment by doronbehar** [comment] 2019-01-07 08:16
Correct @gsantner & @OssNasr, not all people know CSS or JavaScript but I think that this issue should remain closed never the less. My opinion is that an Arabic or Hebrew markdown writer should be aware of the mentioned CSS and the `dir` HTML attribute.

Take Microsoft Word for example, from my experience, it gives one of the worst experiences when trying to handle RTL vs LTR for the user. That's what made me strongly believe in WYSIWYM and markdown is one of the best choices for easy WYSIWYM text formats. The RTL vs LTR issue is a trade-off we should learn to handle because only this way we'll be able to handle it properly - our way.

**Comment by ali-hardan** [comment] 2019-01-07 21:09
This issue can be fixed by three methods:

## 1. Use `unicode-bidi: plaintext` css for all elements

It can done simply by adding it to CSS:

~~~css
* { unicode-bidi: plaintext }
~~~

When you done this, WebView will be behave completly like editor mode and set each paragraph to the correct direction. No more will be needed, It works like a charm :-) I have tested it on Markor.

**Note:** When you use this method, `direction` property in CSS will not work, unless you set `unicode-bidi` to `normal` for your element. Usually `direction` property not needed when you have set `unicode-bidi` to `plaintext`, because it have set element to correct direction.

I have found this at [here](https://github.com/w3c/csswg-drafts/issues/2091).

## 2. Use javascript to set all `dir` attribute of elements to `auto`

Simple:

~~~javascript
window.onload = function(e){
	var elements = document.body.getElementsByTagName("*");

	for(i = 0;i < elements.length; i++) {
		elements[i].dir = "auto";
	}
}
~~~

You can test it on a simple html file, it works, but I don't know why it not effect my text in Markor. I think it because android WebView set `direction` property to `ltr` as default and this method not works until `direction` has been set to `ltr` or `rtl`, It works only when `direction` property are not provided.

## 3. Use xregexp to detect correct direction of paragraph and set it to that using javascript

It works great, but external library needed:

~~~javascript
<script src="https://unpkg.com/xregexp/xregexp-all.js"></script>
<script>
	window.onload = function(e){
		var unicodeLetter = XRegExp("\\p{L}");
		var elements = document.body.getElementsByTagName("*");

		for(i = 0;i < elements.length; i++) {
			var str = elements[i].textContent;
			if (XRegExp.match(str, unicodeLetter) != null) {
				var first_letter = XRegExp.match(str, unicodeLetter).charCodeAt(0);
			} else {
				var first_letter = 0;
			}

			if(first_letter >= 1424 && first_letter <= 1983) 
			{
				elements[i].dir = "rtl";
				elements[i].style.direction = "rtl";
			} else {
				elements[i].dir = "ltr";
				elements[i].style.direction = "ltr";
			}

		}

	}
</script>
~~~

**Note:** I think it only works for Arabic and Persian. For Hebrew, you should edit the code a little.


***

@gsantner, I suggest to use `unicode-bidi: plaintext`. It makes preview behaves like editor, That is what Markor users want. You should drop `rtl rendering` option from settings.

**Comment by OssNasr** [comment] 2019-01-07 21:38
@ali-hardan  I've tried 1 & 2 , it works well, great 😉.
3 seem to be technical, so I haven't try it 😂
Thanks ❤️

**Comment by gsantner** [comment] 2019-01-07 21:39
Thanks for your indepth look. If there is automatic support available, to behave like editor automatically thats even better.

Will try this and if it looks fine I likely will go for removing the RTL option and make all automatically!

Am 7. Januar 2019 22:10:00 MEZ schrieb Ali Hardan <notifications@github.com>:
>This issue can be fixed by three methods:>
>>
>## 1. Use `unicode-bidi: plaintext` css for all elements>
>>
>It can done simply by adding it to CSS:>
>>
>~~~css>
>* { unicode-bidi: plaintext }>
>~~~>
>>
>When you done this, WebView will be behave completly like editor mode
>and set each paragraph to the correct direction. No more will be
>needed, It works like a charm :-) I have tested it on Markor.>
>>
>**Note:** When you use this method, `direction` property in CSS will
>not work, unless you set `unicode-bidi` to `normal` for your element.
>Usually `direction` property not needed when you have set
>`unicode-bidi` to `plaintext`, because it have set element to correct
>direction.>
>>
>I have found this at
>[here](https://github.com/w3c/csswg-drafts/issues/2091).>
>>
>## 2. Use javascript to set all `dir` attribute of elements to `auto`>
>>
>Simple:>
>>
>~~~javascript>
>window.onload = function(e){>
>	var elements = document.body.getElementsByTagName("*");>
>>
>	for(i = 0;i < elements.length; i++) {>
>		elements[i].dir = "auto";>
>	}>
>}>
>~~~>
>>
>You can test it on a simple html file, it works, but I don't know why
>it not effect my text in Markor. I think it because android WebView set
>`direction` property to `ltr` as default and this method not works
>until `direction` has been set to `ltr` or `rtl`, It works only when
>`direction` property are not provided.>
>>
>## 3. Use xregexp to detect correct direction of paragraph and set it
>to that using javascript>
>>
>It works great, but external library needed:>
>>
>~~~javascript>
><script src="https://unpkg.com/xregexp/xregexp-all.js"></script>>
><script>>
>	window.onload = function(e){>
>		var unicodeLetter = XRegExp("\\p{L}");>
>		var elements = document.body.getElementsByTagName("*");>
>>
>		for(i = 0;i < elements.length; i++) {>
>			var str = elements[i].textContent;>
>			if (XRegExp.match(str, unicodeLetter) != null) {>
>				var first_letter = XRegExp.match(str,
>unicodeLetter).charCodeAt(0);>
>			} else {>
>				var first_letter = 0;>
>			}>
>>
>			if(first_letter >= 1424 && first_letter <= 1983) >
>			{>
>				elements[i].dir = "rtl";>
>				elements[i].style.direction = "rtl";>
>			} else {>
>				elements[i].dir = "ltr";>
>				elements[i].style.direction = "ltr";>
>			}>
>>
>		}>
>>
>	}>
></script>>
>~~~>
>>
>**Note:** I think it only works for Arabic and Persian. For Hebrew, you
>should edit the code a little.>
>>
>>
>***>
>>
>@gsantner, I suggest to use `unicode-bidi: plaintext`. It makes preview
>behaves like editor, That is what Markor users want. You should drop
>`rtl rendering` option from settings.>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/gsantner/markor/issues/291#issuecomment-452082808

-- 
Mit freundlichen Grüßen / Best regards,
Gregor Santner
http://gsantner.net/

**Comment by OssNasr** [comment] 2019-01-08 08:06
@gsantner It just works with me in plain text, when writing in markdown, the problem appear again.

![screenshot](https://drive.google.com/file/d/1Vt9zkdbefjjf3UppQaUTCp79eErCPA2D/view?usp=drivesdk)

i think injecting CSS element is the best way.

**Comment by ali-hardan** [comment] 2019-01-08 09:01
@OssNasr, Use this instead:

~~~css
p,h1,h2,h3,h4,h5,h6{unicode-bidi:plaintext}
~~~

But I cannot affect on lists (ol/ul) using this :-(

**Comment by gsantner** [comment] 2019-01-08 09:23
No, not only ol/ul, but also citing! So we have to keep the RTL setting :)

**Comment by OssNasr** [comment] 2019-01-11 16:43
![screenshot_20190111-183321](https://user-images.githubusercontent.com/43766296/51046926-043d0700-15d0-11e9-9a2a-226904c7159d.png)

The script (3. Use xregexp to get first letter of paragraph...👆) is working well except Arabic tables 😥
Anyway, Thank you so much for your help @doronbehar @gsantner @ali-hardan

**Comment by gsantner** [comment] 2019-01-11 17:47
Hey everybody in discussion!

Thanks for working on this, and while I'm open for improving things for RTL.

I'm giving you this to decide what works best, and I happily accept pull request to deliver best experience for RTL!

My requirements are:
* No visible changes for people opening the app (without changing settings) and typing latin/LTR
* No big framework used in representation, and bundle-able. One-Two small open source licensed javascript files for example is fine

**Comment by ali-hardan** [comment] 2019-01-11 18:08
Maybe I will do this, but not soon.

**Comment by OssNasr** [comment] 2019-02-03 19:47
I really appreciate your work Mr. @ali-hardan  , but i have tried that way and it doesn't work well :cry: 
your idea about using xRegExp is the ideal method, if just Mr. @gsantner  include the javaScript code for that library to work offline, its 263.27 KB in size.

tables issue can be fixed in two ways:
- adding `table { margin: auto; }` centering tables.
- adding `table { display: block; }` this will make it follow text rendering according to text inside it.

it would be great if it's optional for users to select either centering table or make it follow text direction.

![screenshot_20190203-211619](https://user-images.githubusercontent.com/43766296/52181601-4686ec00-27fc-11e9-972d-3dbc3050d141.png)
![screenshot_20190203-211722](https://user-images.githubusercontent.com/43766296/52181612-530b4480-27fc-11e9-845c-cc8ac25d6bce.png)

**Comment by ali-hardan** [comment] 2019-02-03 19:56
@OssNasr, What is not work? I have tested it and it seems works completely. What is the problem?

If this work can be done without including external library, we should not include external library.

**Comment by OssNasr** [comment] 2019-02-04 12:01
Actually I hope that app to be as lightweight ASAP, but when trying this approach, sometimes marked text not appear like supposed, I've spent sometime figuring what the problem is...
![screenshot_20190204-135127](https://user-images.githubusercontent.com/43766296/52207036-d83a3c00-2884-11e9-98a7-8d523f77512b.png)
![screenshot_20190204-133350](https://user-images.githubusercontent.com/43766296/52207067-ef792980-2884-11e9-84ba-40328cfd7a87.png)

**Comment by ali-hardan** [comment] 2019-02-04 12:34
@OssNasr, Please send your markdown source here, to I test that.

**Comment by OssNasr** [comment] 2019-02-04 12:54
## ادارة الوقت

1. تحليل الوقت
    اختر اسبوع نموزجي واكتب المهام اليومية كل يوم في ورقة
2.  اختبار الانشطة *الضرورة - الخصوصية - الكفائة*
      مهمة ف الاسبوع
      ضرورية
      ضروري خاص
     كفائة


* حدد وقت الذروة في يومك *العصر - ١٢ ليلا*

* اكتب اهداف (سنوية-شهرية-اسبوعية)، (شخصية - اجتماعية - مهنية - دعوية)
* حدد انشطة لاهدافك - رتبها حسب الاولوية - تخلص من الغير ضروري،
* فوض ما يمكن تفويضه

**Comment by ali-hardan** [comment] 2019-02-04 13:37
@OssNasr, You should put the source in code tag when post it here to above github from rendering. Put your source between `~~~` and `~~~`. Don't forget linebreak after/before this marks. example of using code tag:

~~~
# Hello
**bye**
~~~

**Comment by OssNasr** [comment] 2019-02-04 13:43
Sorry,

```
## ادارة الوقت

1. تحليل الوقت
    اختر اسبوع نموزجي واكتب المهام اليومية كل يوم في ورقة
2.  اختبار الانشطة *الضرورة - الخصوصية - الكفائة*
      مهمة ف الاسبوع
      ضرورية
      ضروري خاص
     كفائة


* حدد وقت الذروة في يومك *العصر - ١٢ ليلا*

* اكتب اهداف (سنوية-شهرية-اسبوعية)، (شخصية - اجتماعية - مهنية - دعوية)
* حدد انشطة لاهدافك - رتبها حسب الاولوية - تخلص من الغير ضروري،
* فوض ما يمكن تفويضه
 ```

**Comment by ali-hardan** [comment] 2019-02-04 14:11
Now test it, it seems fixed:

~~~html
<script type="text/javascript"> 
	function onPageLoaded(){ 
		var elements = document.body.querySelectorAll(":not(li) > p,ol,ul,h1,h2,h3,h4,h5,h6");
		for(i = 0;i < elements.length; i++) {
			elements[i].dir = "auto";
		}

		var elements = document.body.getElementsByTagName("table");
		for(i = 0;i < elements.length; i++) {
			var div = document.createElement("div");
			div.dir = "auto";
			elements[i].parentNode.insertBefore(div, elements[i]);
			div.appendChild(elements[i]);
		}
	}
</script>
~~~

if You see problem in tables, post example.

**Comment by OssNasr** [comment] 2019-02-04 14:21
**Great** , it works well,  tables also work wel,
A new issue is : blockquotes  should be right borderd in RTL rendering, have you an approach ?

**Comment by ali-hardan** [comment] 2019-02-04 14:50
Good issue. There are exists [:dir() CSS pseudo-class](https://developer.mozilla.org/en-US/docs/Web/CSS/:dir). Using it in css, this issue can be done simply. But the problem is: this CSS pseudo-class currently not supported in most of modern browsers, including Android WebView. Currently only Firefox supports this, and in the future, other borwsers will support it.

We can do it using javascript hack (maybe should use external library), but I think it would better to let's take this feature off, until web browsers add support of this CSS pseudo-class. This is not important feature and not affect on our usage.

***

I have edited previous javascript a little, it is better:

~~~html
<script type="text/javascript"> 
	function onPageLoaded(){ 
		var elements = document.body.querySelectorAll(":not(li):not(blockquote) > p,blockquote,ol,ul,h1,h2,h3,h4,h5,h6");
		for(i = 0;i < elements.length; i++) {
			elements[i].dir = "auto";
		}

		var elements = document.body.getElementsByTagName("table");
		for(i = 0;i < elements.length; i++) {
			var div = document.createElement("div");
			div.dir = "auto";
			elements[i].parentNode.insertBefore(div, elements[i]);
			div.appendChild(elements[i]);
		}
	} 
</script>

~~~

***

If somebody wants to use CSS pseudo-class for bordering blockquote correctly, here is CSS:

~~~CSS
blockquote:dir(ltr) {
	padding:0px 14px;border-left:3.5px solid #dddddd;
}
blockquote:dir(rtl) {
	padding:0px 14px;border-right:3.5px solid #dddddd;
}
~~~

**Currently, it only works on Mozilla Firefox**

**Comment by OssNasr** [comment] 2019-02-04 15:01
the problem with me is that my phone is forced to use Chrome WebView instead of Android WebView, I don't know why Google wanna take own :angry:

**Comment by gsantner** [comment] 2019-02-04 15:24
Hi everybody, thanks for active work and discussion in this.
Please mention me (`@gsantner`) when you have sonething that works for you mutual.

In general, I prefer a 95% working solution with some js/css lines to a library, as sharing  doesnt include additional libraries and files (but does custom fixed and stuff;) ).

**Comment by OssNasr** [comment] 2019-02-04 15:31
Google now going everywhere , this could explain what i mean :
[While we blink, we lose the web](https://andregarzia.com/2018/12/while-we-blink-we-loose-the-web.html)

**Comment by OssNasr** [comment] 2019-02-04 19:50
I think we can't fix `blockquote` the way you mentioned Mr. @ali-hardan , simply because there is two conditions
1. If we didn't adjust its direction, it will be LTR by default.
2. If we adjust it to auto, it will be `auto`.

Then, there is no `rtl` value to look for.
We can skip it BTW , I'm rearly use it.

**Comment by ali-hardan** [comment] 2019-02-04 20:00
@OssNasr, What you say is not correct. `:dir() pseudo-class`, detects affected direction, not defined direction. So, when we set `dir` Attribute to `auto`, if text rendered as RTL, `:dir(rtl)` affect on it. and when text rendered as LTR, `:dir(ltr)` affect on it.

You can test it on Firefox to see how it works.

**Comment by OssNasr** [comment] 2019-02-04 20:03
I hope that, you ate genius 🙂 💪
I hope it works well, thanks for your work 🙂

**Comment by gsantner** [comment] 2019-07-22 19:47
If there is a final conclusion / a working solution for all required cases, please comment it.

Closing this issue as it looks to me there is no change required.

**Closed by gsantner** 2019-07-22 19:47 UTC
