### ISSUE TITLE
Share Into: Markor does not detect duplicate strings in EXTRA_SUBJECT and EXTRA_TEXT

### ISSUE THREAD

**Issue by madalu** [gsantner/markor#1401] opened 2021-07-28 22:51 UTC
## General information
* App version: 2.7.0
* Android version: 11

### Description

When sharing a link some apps (e.g., Wallabag) put the title/description of the link both in EXTRA_SUBJECT and EXTRA_TEXT, as in this screenshot: 

![2021-07-28_15-48](https://user-images.githubusercontent.com/2131453/127393820-4e7efe5e-66f2-4102-b89f-c66038872429.png)

With Markor 2.6.0 and early, Markor detected this duplicate subject string and ignored it to avoid redundancy. The resulting text inserted in the markdown file looked like this:

      Markor - Project Website & FAQ - Markdown Editor, todo.txt, Android app https://gsantner.net/project/markor.html

This detection was removed with commit 592181e695c2932c90b12ae2bc969116545564ac. As a result the same link shared into Markor 2.7.0 now results in this text:

     Markor - Project Website & FAQ - Markdown Editor, todo.txt, Android app Markor - Project Website & FAQ - Markdown Editor, todo.txt, Android app https://gsantner.net/project/markor.html

Note that neither the earlier nor current version detected that this was a link. 

There are issues and PRs related to this in the Wallabag repo (https://github.com/wallabag/android-app/issues/536 and https://github.com/wallabag/android-app/pull/538), but some Wallabag developers are of the opinion that putting the title in both places is correct and avoids problems when sharing to other apps.

**Comment by gsantner** [comment] 2021-07-28 22:57
As you already see, it's hard to find a <<best solution>> to this, as it differs a lot from source app to source app, and target app to target app. I'd also suggest to use the correct variables for the correct thing (at source) instead of 1:1 duplicating.

**Comment by madalu** [comment] 2021-07-29 16:41
Thanks so much for the response. I agree that the norm in Android is not to duplicate things at the source. I made a comment over in the Wallabag PR, which is ideally where this will be changed. 

Regarding Markor, was the previous behavior of discarding EXTRA_SUBJECT if its string was found in EXTRA_TEXT an intended feature?

**Comment by gsantner** [comment] 2021-07-29 17:09
It was intended, I developed it. However it was hacky.

**Comment by gsantner** [comment] 2021-09-08 20:52
Closing as it looks pretty specific to a external app, works fine i.e. when sharing links from browsers.

**Closed by gsantner** 2021-09-08 20:52 UTC
