### ISSUE TITLE
Add ability to view/convert File Encoding and Line Endings

### ISSUE THREAD

**Issue by SumatraPeter** [gsantner/markor#1274] opened 2021-03-06 00:47 UTC
#### General information

* **App version:** v2.6.0 (122) via F-Droid
* **System:** Android 5.0.1

#### Description

All of a sudden during the pandemic I'm caught in a bit of a bind with my laptop on the fritz and only my Android tablet to work on. The problem is that my stupid TV seems to accept text format subs (SRT  etc.) only with ANSI encoding and Windows (CRLF) line endings. Crazy, I know.

So I was hoping Markor could gain the ability to do the following:

* View the current file encoding and switch to a different one (with data loss warnings if necessary like when UTF-8 files with non-ANSI chars are converted to ANSI).
* View the current newline/line ending style (Windows: CRLF vs *NIX: LF) and switch to a different one.

**Comment by harshad1** [comment] 2021-03-07 00:44
for line endings, you may be able to use the search - replace

**Comment by SumatraPeter** [comment] 2021-03-07 04:41
@harshad1: Using `\n` and `\r\n` as the search and replace terms respectively did seem to make some difference based on the file size increasing a bit, but ideally speaking:

1. There needs to be an a clear indicator of the current line ending style.
2. It would be _much_ better if the conversion between styles was inbuilt rather than requiring a search-replace.

Testing this also reminded me that Markor struggles with 'large' files, by which I mean something even a few 100 KBs in size. The ~160 KB SRT was slow to load with the screen going blank and no loading progress indication, and slow to search-replace with the bottom icon toolbar repeatedly going wonky and jumping up and down. Also this is the first time I've really paid attention to the search-replace UI. Displaying the entire file as scrollable text in the dialog doesn't seem like a great idea when the app's already struggling with that much text.

**Comment by harshad1** [comment] 2021-03-07 05:24
I can confirm (checked in vim) that search-replace does change the line endings.

I do not think Markor will support other line endings any time soon as Android and Markor expect LF line endings in much of the text manipulation logic, and various parts will break if you use CRLF or CR.

The performance issues are a whole separate thing which I have been trying to address as and when I come up against them in my usage of Markor. As @gsantner will point out, contributions are welcome :)

Finally, and on a different note, have you considered using an awk script in Termux to fix the encoding and line ending issue? I suspect it will be the fastest way for you to solve your issue.

**Comment by SumatraPeter** [comment] 2021-03-08 00:36
Can't install Termux on this Android L tablet with non-Neon Intel Atom chip. :(

**Comment by gsantner** [comment] 2021-03-13 13:48
Closing as duplicate of  #827 - please use search.

My suggestion: Determine `\r\n # \r # \n`, replace everything with `\n` at markor usage, and at file save time use the original one again.

**Closed by gsantner** 2021-03-13 13:48 UTC
