### ISSUE TITLE
Issue with latest version not installing on Android Motorola

### ISSUE THREAD

**Issue by Breakout-X** [gsantner/markor#2465] opened 2024-10-30 15:12 UTC
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [x] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

The app won't install. The error is "`Something Went Wrong - App not installed`".

I tried searching for similar issues and could not find one.

### Steps to reproduce

1. Open GitHub Releases
2. Click on the APK (successfully downloads without virus warning, indicating that it's safe)
3. Attempt to install APK

### Information

Android version: 13/0 (It says version 13 and version 0)
Device: Android Motorola
App Version: v2.13.0

### Source

GitHub Releases

### Format / File type

Something else (-> Additional info)

### Additional info / Log

The previous version works fine, but the latest won't install. Markor is a good app, but it won't update for whatever reason.

**Comment by gsantner** [comment] 2024-10-30 16:36
It installed just fine here. Are you sure you previously installed from here and not F-Droid i.e.?

**Comment by Breakout-X** [comment] 2024-10-30 16:54
> It installed just fine here, I use the GitHub one myself too. Are you sure you previously installed from here and not F-Droid i.e.?

Yes I am sure. I got it from this link with this id: “[`net.gsantner.markor-v155-2.13.0-flavorDefault-release.apk`](https://github.com/gsantner/markor/releases/download/v2.13.0/net.gsantner.markor-v155-2.13.0-flavorDefault-release.apk)”.

I tried installing it 3 times before creating this issue. I’ll try again right now.

**Comment by Breakout-X** [comment] 2024-10-30 17:05
> It installed just fine here, I use the GitHub one myself too. Are you sure you previously installed from here and not F-Droid i.e.?

Here's a screenshot (ignore the blurred text):
![Screenshot_20241030-125713~2](https://github.com/user-attachments/assets/3af3b7cc-d24f-48eb-acfb-e64f9172b104)

**Comment by gsantner** [comment] 2024-10-30 17:07
I keep it open, maybe someone else has the issue too.

What you can try is installing from computer with `abd install -r`

**Comment by Breakout-X** [comment] 2024-10-30 17:09
> I keep it open, maybe someone else has the issue too.
> 
> What you can try is installing from computer with `abd install -r`

Does `abd` require administrative permissions? Although I do work with NodeJS, I am currently not the admin of my computer, and it took a year to get permission for simply just NodeJS.

**Comment by gsantner** [comment] 2024-10-30 17:18
I don't think so, its a archive download and should be portable with user rights usable.

**Comment by Breakout-X** [comment] 2024-10-30 17:20
> I don't think so, its a archive download and should be portable with user rights usable.

Oh, so like how Git-Bash was distributed? That works. Where can I download it from?

**Comment by Breakout-X** [comment] 2024-11-01 11:48
> I don't think so, its a archive download and should be portable with user rights usable.

By the way, I tried installing Marder and it worked.

https://github.com/user-attachments/assets/12056076-3004-40c8-89cc-958ea092493d

**Comment by Breakout-X** [comment] 2024-11-01 11:56
> I don't think so, its a archive download and should be portable with user rights usable.

Since I have APK Explorer and Editor, would you be okay if I checked your code in the APKs to see if there's any key difference that might be causing the issue?

(I'm asking for your permission to respect your ownership of the app because APK Explorer and Editor allows me to modify apps)

If your app is built with JavaScript or NodeJS in some way, I could definitely help with it somewhat.

**Comment by gsantner** [comment] 2024-11-01 13:49
I don't have a Motorola device and can't reproduce the installation issue.

If somebody has interest or know a bit how to compile android apps with Andtoid Studio feel free to, you might discover somethimg.

The permission stuff is/should be complete unrelated to Breakout-X's topic (offtopic).

**Comment by Breakout-X** [comment] 2024-11-01 18:54
> I don't have a Motorola device and can't reproduce the installation issue.
> 
> If somebody has interest or know a bit how to compile android apps with Andtoid Studio feel free to, you might discover somethimg.
> 
> The permission stuff is/should be complete unrelated to Breakout-X's topic (offtopic).

I'll use APK Explorer and Editor on my phone as I don't have Android Studio on my PC, and my NodeJS APK Editor is a work-in-progress. However, if I ever get Android Studio, I'll let you know what happens from there.

**Comment by pudah** [comment] 2024-11-12 19:19
I have a Motorola device on Android 12. I usually install Markor via F-droid. I've had version 2.13 installed for a few days now without incident.

I tried to duplicate this issue.

I uninstalled the F-droid version. Downloaded `net.gsantner.markor-v155-2.13.0-flavorDefault-release.apk` from here on github. I installed it successfully. No errors during install. No errors granting file permission. No errors on launching the app. No errors in quick test of normal app use.

**Comment by gsantner** [comment] 2024-11-12 19:21
Thanks for testing. Not sure whats wrong at those few users with the issue.

**Comment by gsantner** [comment] 2024-11-15 16:14
Closing, it seems not like there is a general issue with the download.

Can only recommend to try installation from other source / uninstall / reinstall.

Recommended installation source as always is from F-Droid.

**Closed** 2024-11-15 16:15 UTC

**Comment by Breakout-X** [comment] 2024-11-17 00:07
> Closing, it seems not like there is a general issue with the download.
> 
> Can only recommend to try installation from other source / uninstall / reinstall.
> 
> My recommended installation source is as I always say - F-Droid.

Okay. I'll try reinstalling from F-Droid. Also, what exactly is the difference between Markor and Marder? Marder seems to work perfectly fine

**Comment by gsantner** [comment] 2024-11-17 00:14
Marder is a testbuild/debug build.

**Comment by Breakout-X** [comment] 2024-11-17 01:29
> Marder is a testbuild/debug build.

Is that the only difference? If it is, I'll keep using Marder for now

**Comment by Breakout-X** [comment] 2024-11-18 11:38
> Marder is a testbuild/debug build.
> 

I did install from F-Droid and although it threw an error the first attempt to install, the second attempt worked.
I noticed that the GitHub version and the F-Droid are 1 MB different although they are the exact same version. Whatever is in the 1 MB is probably what's preventing me from downloading the GitHub version.
