### ISSUE TITLE
QuickNote.md - window 'bounces' on each input event

### ISSUE THREAD

**Issue by contrapunctus-1** [gsantner/markor#191] opened 2018-02-10 05:17 UTC
Markor v0.3.2 from F-Droid, on a Moto G5s Plus running Android v7.1.1. I have tested this with AnySoftKeyboard, Hacker's Keyboard, and the AOSP Indic keyboard.

1. Add >5 lines to QuickNote.md.
2. Move cursor to anywhere in the middle of the text (i.e. it should be succeeded by non-whitespace characters)
3. Make input events. Be it tapping in the text area, or moving the cursor (using AnySoftKeyboard's arrow keys), or inserting or deleting text, each event causes the window to bounce up and down wildly. This seems to vanish in the first few lines of the file, and get progressively worse as one attempts these operations in the later lines.

**Comment by gsantner** [comment] 2018-02-10 08:24
I cannot reproduce your problem on any device. Maybe somebody else can.

**Comment by kRkk** [comment] 2018-02-10 10:54
I also have this problem

**Comment by kRkk** [comment] 2018-02-10 11:03
I also have this problem with Hacker's Keyboard and Google Keyboard but not only in QuickNote, To-Do has the same problem

**Comment by kRkk** [comment] 2018-02-10 11:04
Unhiding statusbar in editor fixes problem

**Comment by kRkk** [comment] 2018-02-10 11:04
Unhiding the status bar in the editor mode solves the problem

**Comment by gsantner** [comment] 2018-03-17 07:43
This is due Android Bug nr. 5497 which seems to not be fixed on your device, hence an Workaround kicks in (<https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/util/AndroidBug5497Workaround.java>), so the app works at all using no-statusbar.

Nothing anybody can do about.

**Closed by gsantner** 2018-03-17 07:43 UTC
Labels: wait/maybe/upstream
