### ISSUE TITLE
space in front of shared text

### ISSUE THREAD

**Issue by Simplenuity** [gsantner/markor#1791] opened 2022-08-15 10:02 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

If I'm not mistaken since update of Markor to 2.10.1 I encounter the following:
When I select text in one of my apps (for example Blinkist), then choose the option to share it with Markor the text shows up in the Markor window as selected(1). If I select Quicknote and then open the Quicknote there has been a space added in front of the text.

(1) except sharing from a browser where independent of selection the title and webpage link gets presented. But that might be another issue?

In general: Outstanding app! Highly appreciate the huge effort you put into it. Thank you!

### Steps to reproduce

1. select text in an app that offers the option to select and share like k-9
2. select share -> Markor
3. in Markor select sharing as Quicknote
4. open the Quicknote: in front of the shared text there is a space added

### Information

Android version: 10
Device: Xiaomi Mi Max 3
App Version: 2.10.1

### Source

Google Play

### Format / File type

Plaintext

### Additional info / Log

```shell
Please let me know what other information you need.
```

**Comment by gsantner** [comment] 2022-08-15 10:35
do you have a custom share-into template set in Markor settings?

**Comment by Simplenuity** [comment] 2022-08-15 11:13
The answer most likely is yes.
When I choose 'Quicknote' it saves it in a txt specific file within a Zim notebook that gets synced with Syncthing.
Most likely as I just noticed that I can't open the Markor settings to check ... the app crashes as soon as I tap 'settings' (shall I open a new issue for that?)

**Comment by gsantner** [comment] 2022-08-15 11:18
> app crashes as soon as I tap 'settings' (shall I open a new issue for 
that?)

No it is fixed on master already. Generally the main distribution of 
Markor is at F-Droid, that version doesn't have the bug :smiley: . 
<https://gsantner.net/blog/2022/07/16/markor-v2.10-custom-file-templates-share-into-remove-tracking-parameters.html#how-to-install--update-markor>

**Comment by Simplenuity** [comment] 2022-08-15 11:43
Thanks, I'll change to F-Droid immediately :) It's preferred anyway

**Comment by gsantner** [comment] 2022-08-20 06:20
please close when you don't encounter it anymore. generally looks like some unintentional setting set.

**Closed** 2022-08-20 18:29 UTC
Labels: invalid/duplicate

**Comment by Simplenuity** [comment] 2022-08-21 09:40
Hi again, the crash I don't experience anymore, but the space in front of shared text. Are you saying it's due to an unintentional setting on my end?

**Comment by gsantner** [comment] 2022-08-22 11:19
I tried it in the latest release with original settings and it works correctly all I see. It adds Newline+separator as the default is. And no unrelated space character .

**Comment by Simplenuity** [comment] 2022-08-23 03:58
I'll test again after I can install your newest release (2.10.3) via f-droid. 
2.10.2 is crashing when opening settings and has other issues, too

Thanks for all your work!

**Comment by gsantner** [comment] 2022-08-23 22:55
yes the new architecutre (androidX) and related changes are huge, more side-effects in different cases and devices.

**Comment by Simplenuity** [comment] 2022-08-25 01:21
If I may ask, how long does it usually take till a new release on here shows up over at F-Droid? 2.10.3 unfortunately hasn't shown up yet. I'm desperately waiting in the hope it will make Markor usable again.

**Comment by gsantner** [comment] 2022-08-25 03:03
Out of control. 3d usually.

**Comment by Simplenuity** [comment] 2022-08-25 08:34
I assumed it's not under your control.
Thanks, good to know. Hanging in about another day...

**Comment by Simplenuity** [comment] 2022-08-27 03:28
Updated to 2.10.3 via F-Droid.
Lagging is gone which made app unusable (2.10.2), but trying to open settings is still making the app crash

Shall I open a new issue?

Here the error message:

> java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2578828 bytes
 at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:224)
 at android.app.ActivityThread.main(ActivityThread.java:7562)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.os.TransactionTooLargeException: data parcel size 2578828 bytes
 at android.os.BinderProxy.transactNative(Native Method)
 at android.os.BinderProxy.transact(BinderProxy.java:510)
 at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4646)
 at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
 ... 7 more

**Comment by gsantner** [comment] 2022-08-27 08:54
How much characters does your QuickNote and ToDo file each have?

**Comment by Simplenuity** [comment] 2022-08-27 13:24
around 600000 characters (650kB)
I point QuickNote and ToDo to the same file

Using a nearly empty file (0.3kB) allowed me to open Settings without crash!

But that space at the beginning of shared text below the separation line still shows up when I open the file.
After deleting the GooglePlay version and installing from F-Droid the 'Save location' settings got reset to defaults. So I assume I did start with the original settings...
Will run a few more tests, also on another device.

**Comment by Simplenuity** [comment] 2022-08-27 13:57
Just tested sharing a website link from within a browser with Markor (2.10.3 via F-Droid) on Samsung Tab3 with Android 7.1.2 (LineageOS 14.1) with default settings in Markor: same behaviour - there is a space at the beginning of shared text below the separation line when I open QuickNote.

**Comment by gsantner** [comment] 2022-08-27 15:04
screenshots are sometimes very helpful.

**Comment by gsantner** [comment] 2022-08-27 15:08
screenshots are sometimes very helpful. so please share some instead of rehashing it multiple times. might be it's working as expected.


This is how it's expected to work, and does here. And I fresh installed Markor recently (because I swapped from F-Droid to my self built apk to test).


```
----
 [geizhals](https://geizhals.at/?cat=nb&xf=11293_06+16+-+RTX+3070~11293_06+16+-+RTX+3070+Ti~11293_06+16+-+RTX+3080~11293_06+16+-+RTX+3080+Ti~12_8192~15313_RGB+beleuchtet~2379_17~31_RJ-45~6751_26~6751_27&sort=t&hloc=at&hloc=de&v=e&t=v&bpmax=2200 )

----
 [News - News & Blog - TUXEDO Computers](https://www.tuxedocomputers.com/de/Infos/News.tuxedo ) --> https://linuxrocks.online/@tuxedocomputers

----
```

![grafik](https://user-images.githubusercontent.com/6735650/187036021-a6608c2d-f18b-4956-a2ae-b60a355d77ec.png)

**Comment by gsantner** [comment] 2022-08-27 15:24
@harshad1 

I remember adding some if > 400/500kb check or something at the saveinstancestate stuff (due the 1MB activity limit). Can you remember where that went or why it got removed? I see TransactionTooLargeException fairly often

> java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2578828 bytes
> around 600000 characters (650kB) 

![grafik](https://user-images.githubusercontent.com/6735650/187036620-4d8664ed-fabd-4c46-bb2f-885bdfdba21b.png)

**Comment by gsantner** [comment] 2022-08-27 15:26
@Simplenuity
screenshots are sometimes very helpful. so please share some instead of rehashing it multiple times. might be it's working as expected.

This is how it's expected to work, and does here. And I fresh installed Markor recently (because I swapped from F-Droid to my self built apk to test).  (btw the geizhals newline is from myself) The thing is, you are the only one I currently know with such a problem. Sounds like you are hunting a issue which is none ^^.


```
----

 [geizhals](https://geizhals.at/?cat=nb&xf=11293_06+16+-+RTX+3070~11293_06+16+-+RTX+3070+Ti~11293_06+16+-+RTX+3080~11293_06+16+-+RTX+3080+Ti~12_8192~15313_RGB+beleuchtet~2379_17~31_RJ-45~6751_26~6751_27&sort=t&hloc=at&hloc=de&v=e&t=v&bpmax=2200 )

----
 [News - News & Blog - TUXEDO Computers](https://www.tuxedocomputers.com/de/Infos/News.tuxedo ) --> https://linuxrocks.online/@tuxedocomputers

----
```

![grafik](https://user-images.githubusercontent.com/6735650/187036021-a6608c2d-f18b-4956-a2ae-b60a355d77ec.png)


>  I point QuickNote and ToDo to the same file

Generally? You should not do that. That will sooner or later result in data loss as both load/save at nearly same time on start screen. Don't do that.

**Comment by harshad1** [comment] 2022-08-27 16:28
Hmmm. I don't explicitly remember removing it. Doesn't mean I didn't accidentally remove it though...

What are we even serializing that is so large? I thought it was just a couple flags in the document class. Document edit fragment uses App settings for onPause state...

If I figure out the cause, I'll add a fix in my pr.

Aug. 27, 2022 08:24:24 Gregor Santner ***@***.***>:

**Comment by gsantner** [comment] 2022-08-27 16:48
In the past there used to be a copy of the string stored in the Document 
class. Which I think was removed at some point. But seems like there is 
still something around that is put into savedInstance, (either the 
string or similar bytesized object)


Am 27.08.22 um 16:28 schrieb Harshad Vedartham:

**Comment by harshad1** [comment] 2022-08-27 17:11
Hmm. I think textview may be doing this internally.

I'll check.

Thanks for finding this.

Aug. 27, 2022 09:48:48 Gregor Santner ***@***.***>:

**Comment by gsantner** [comment] 2022-08-27 17:15
hmm maybe some new androidx behaviour? at least previously transactiontoolarge would only happen when putting data self at activity/fragment

**Comment by harshad1** [comment] 2022-08-27 17:33
I did add code to remove all spans on saveInstanceState. May have to look at saving text externally too

Aug. 27, 2022 10:15:18 Gregor Santner ***@***.***>:

**Comment by gsantner** [comment] 2022-08-27 17:34
only what gets added to activity save cache should be relevant...generally not-yet unfreed memory/GC shouldn't be the issue

**Comment by harshad1** [comment] 2022-08-27 18:27
Ok. I see it. EditText will internally save the entire contents to the Parcellable. There is a flag to prevent this in TextView. But the flag is ignored for edit text.

Am going to have to create a hack to prevent this and force reload from file only.

Aug. 27, 2022 10:34:50 Gregor Santner ***@***.***>:

**Comment by gsantner** [comment] 2022-08-27 18:29
we already deregister all listeners, dont we? = setText("")

**Comment by gsantner** [comment] 2022-08-27 18:29
we already deregister all listeners at onStop/Pause, dont we? => setText("")

**Comment by Simplenuity** [comment] 2022-08-28 08:43
@gsantner 
Fair enough (screenshots - see below) and thanks for the heads-up (only using one file - I changed it)

Using the share option of Blinkist and choosing Markor.
Markor share interface:
![Markor_share_interface](https://user-images.githubusercontent.com/13347943/187064996-89a56909-a183-452e-8531-98ce230caa18.jpg)

Result in file opened in Markor:
![Markor_result_in_file](https://user-images.githubusercontent.com/13347943/187065028-6295892d-ebc6-48ab-960d-7c0b9b267615.jpg)

Using the share option of Blinkist and choosing Markor. Adding manual header format for Zim wiki.
Markor share interface:
![Markor_share_interface--manual_formatting](https://user-images.githubusercontent.com/13347943/187065124-2e2fcc4a-14cd-4824-9693-3e21d3c65dba.jpg)

Result in file opened in Markor:
![Markor_result_in_file--manual_formatting](https://user-images.githubusercontent.com/13347943/187065164-6e2f4d71-36b2-46c5-8f1e-6b55eb04f0ec.jpg)

Result in file opened in Zim wiki:
![Zim_wiki--result--with_space](https://user-images.githubusercontent.com/13347943/187065504-7351118f-705c-4731-8db2-bdd93d4fdb5d.png)

The space prevents the formatting to be recognised. Without space it looks like this in Zim wiki:
![Zim_wiki--result--without_space](https://user-images.githubusercontent.com/13347943/187065250-db7ca925-49ab-4880-9dec-454e248fd523.png)

Currently I can't pinpoint the Markor version this behaviour started to show up with. But for many (older) versions it did not happen. The Markor settings did not get changed. Don't know whether other system settings/updates could cause this?

**Comment by Simplenuity** [comment] 2022-08-28 12:27
@gsantner 
So looking at your example it is actually expected that there is a space added?
![image](https://user-images.githubusercontent.com/13347943/187074101-31a103f8-e751-479c-9561-c1fa21c9351b.png)

**Comment by gsantner** [comment] 2022-09-08 23:33
from  #1495

**Comment by gsantner** [comment] 2022-09-08 23:34
from  #1495 . btw the position and spaces or whatever character is freely controllable by settings option. Just add `%s` where you want to place shared text.

**Comment by gsantner** [comment] 2022-09-08 23:50
@Simplenuity   
Check it out with the next Markor update once it's out

**Comment by Simplenuity** [comment] 2022-09-09 01:23
Thanks @gsantner! Will do

**Comment by Simplenuity** [comment] 2022-09-17 04:05
Thanks @gsantner, have updated (v2.10.4 (140)) and it's working, i.e. no space anymore. And the flexibility to customize the share to string can come in very handy.
Thanks for your patience and great work!
