### ISSUE TITLE
Problems receiving file intents (several apps)

### ISSUE THREAD

**Issue by troyengel** [gsantner/markor#439] opened 2018-11-25 18:40 UTC
#### General information

* **App version:**  1.4.0
* **System:** Pixel 2 (stock Android 9)

#### Description

I'm having problems with consistent and reliable file sending into Markor, I've tried to reproduce this in several ways with different sending apps. In general, it feels like Markor has trouble receiving file intents sometimes, while other editors can receive them fine. I'm not sure where the bugs lie, I realize that they may be with the other apps so just trying to gather information.

I first added [Editor](https://github.com/billthefarmer/editor), a very basic open source editor which seems to receive the file intents from all the below OK (except LabCoat) as an A / B test against Markor at the same time.

  - When I email a file `test.md` to my phone as an attachment and open it in the stock GMail app, the only option to open the file as a share or save is Editor - Markor doesn't even register as a receiver from GMail for *.md it appears?
  - Saving `test.md` to Downloads, then using the "Files" app (built-in basic file app that comes with Android9/Pixel2) when choosing "Open with..." the option for Markor is not present, but Editor is (as well as FX Textedit and FX Text Viewer, part of FX File Manager app)
  - Using [Green Git Client](https://play.google.com/store/apps/details?id=uk.jhutil.ggc) I can clone a project with MD files, navigate to them and attempt to open the file. The file opens straightaway in Editor, but when choosing Markor I get an error about the file not being sent correctly - [`filemanager_doesnot_supply_required_data__appspecific`](https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/markor/activity/DocumentActivity.java#L121) code path. As the Editor source is also open, this was a very good A / B test - Markor _should_ be able to receive the same file as Editor did?
  - Using [LabCoat](https://gitlab.com/Commit451/LabCoat) results in the same error as above about missing file intent data, however this app does not let me choose which app to launch when editing (it always just launches Markor). This project has a lot of bugs open, this may be on their end since I can't test an alternate app (Editor) against it so this one is dubious

The only counter-example of "seems to work right" is when using [FX File Explorer](https://play.google.com/store/apps/details?id=nextapp.fx), however this app uses a different method than most others (you have to choose "Open as..." then select a MIME type `text/plain`, then choose the app to receive - both Markor and Editor receive the file intent fine this way). This app is not open source and has different behaviour traits - interesting, but maybe not useful for this debugging.

Perhaps if nothing else, figuring out why another open source editor (Editor) receives the file intents OK from "GMail" and "Files" stock Android/Google apps would be a clue as to what's going on with Markor's basic file-opening issues. Green Git Client doesn't seem to have source to look at yet (it's alpha), but is an interesting "why doesn't this work either with Markor?". LabCoat's source seems like they copied it from another project so it's an outlier here. Thanks for listening!

**Comment by troyengel** [comment] 2018-11-25 20:43
(trying to help do some legwork) - it appears that modern Android now uses the mime type from [RFC 7763](https://tools.ietf.org/html/rfc7763) `text/markdown`, which I am not seeing in the Markor AndroidManifest.xml. The Android mappings being used are located here now:

* https://android.googlesource.com/platform/libcore/+/master/luni/src/main/java/libcore/net/mime.types#744
* https://android.googlesource.com/platform/libcore/+/master/luni/src/main/java/libcore/net/android.mime.types

These are pulled in from the [MimeTypeMap](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/webkit/MimeTypeMap.java) and parsed, so if we add that it should help. The Editor project is accepting [`text/*`](https://github.com/billthefarmer/editor/blob/master/src/main/AndroidManifest.xml#L32) which makes sense why it works -- the Android subsystem is not sending the file as type `text/plain` but as `text/markdown`, so Markor doesn't get triggered as it's not built to accept that mime type (that I can tell, not an android coder :) ).

I also managed to find [another link](https://answers.unity.com/questions/896012/how-to-make-you-android-app-open-xml-files.html) that shows using a `+extension` method to a mime type is pretty common (?), he shows his solution to read XML files was `<data android:mimeType="application/xhtml+xml" />` (adding the `+xml` after the type) which may or may not help here, possibly adding the `text/plain+md` mapping would be enough. I think that would at least allow the default Google apps to show Markor as an intent receiver to get started...  hope this helps!

**Comment by troyengel** [comment] 2018-11-26 03:37
I found another open source editor [Simple Markdown](https://github.com/wbrawner/SimpleMarkdown) and was able to test, it works correctly and receives the file intents from the GMail and Files apps, GGC and LabCoat as well. Once I installed it, I was then able to choose which editor to launch from LabCoat again so can now confirm Editor works fine there.

**Comment by gsantner** [comment] 2018-12-04 09:58
@troyengel 
Thanks for report and doing research & testing!
The reason is that (as you probably noticed already) Markor is only registered with text mimetypes. If other apps not set that (they should do that) Android won't list Markor.

**Comment by gsantner** [comment] 2018-12-09 19:09
@troyengel 
Have added some mimetypes, checkout next update release if it works better for you ;)

**Comment by troyengel** [comment] 2018-12-11 00:05
Looking good for step 1 - using the two test cases above with the stock phone apps: can I open from the GMail app, and can I open using the Files app from /sdcard/Downloads/. Both now show Markor as a possibility for `test.md` as expected, the new mimetypes work.

Alas, both still launch Markor and I get the error message posted in the first comment, for some reason Markor does not like the way the GMail and Files apps pass the file handle over to Markor via the intent. If you simply file-attach a test.md and email it to yourself, do you see the same results? (wondering if this is an Android 9 specific problem?)

**Comment by contrapunctus-1** [comment] 2019-06-27 10:10
Possibly the same issue when sending a Markdown file using Conversations and trying to open it with Markor. Markor opens the sent file on the sender's Conversations (Nokia 6.1) just fine, but on the receiver's Conversations (Samsung J7 Prime) it says that it can only open local files. The Conversations lead developer said that this was a Markor issue.

**Comment by gsantner** [comment] 2019-06-27 14:34
Can you please send me such a file to xmpp:gsantner@trashserver.net

**Comment by gsantner** [comment] 2019-06-28 11:32
Had a chat with contra, could not resolve the issue so far. Seems to be a device specific issue I can't reproduce.

**Comment by gsantner** [comment] 2019-07-22 19:50
Closing in favor of #197 . Please comment there if required.
Conversations: Cannot reproduce the issue as said, so expect this a device specific issue.

**Closed by gsantner** 2019-07-22 19:50 UTC
Labels: q/discussion/feedback
