### ISSUE TITLE
v2.12.0+: Multiple Windows feature always active

### ISSUE THREAD

**Issue by izzytechie** [gsantner/markor#2286] opened 2024-05-18 07:00 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a [question or feature request](https://github.com/gsantner/markor/issues/new/choose).
- [X] The topic is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=#js-issues-search). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.
- [X] The bug is still present in the latest development version (git master). (Please [download](https://nightly.link/gsantner/markor/workflows/build-android-project/master) and try the test version of Markor, named **Marder**. Don't worry; Markor and Marder appear as completely separate applications. You can install both side-by-side, and Markor settings are not touched. In case the issue is resolved there, you don't need to create a bug report. The change will be part of the next Markor update.)

### Description

Deactivating the Settings -> General -> Features -> Multiple Windows feature has no effect. The Multiple Windows feature is always on.

### Steps to reproduce

1. Deactivate the Settings -> General -> Features -> Multiple Windows feature.
2. Open a file within the Markor app.
3. Switch to Android's Recent Apps screen. 
4. Observe that the Markor app is using multiple windows.

### Information

Android version: 10
Device: Oukitel C21
App Version: 2.12.0

### Source

Google Play

### Format / File type

Not specific

### Additional info / Log

```shell
-
```

**Comment by harshad1** [comment] 2024-05-26 04:28
I can't reproduce this on master.

I'm on a pixel 7 pro with Android 14

**Comment by gsantner** [comment] 2024-05-26 07:01
Have you unchecked the multi window option and closed/swiped out everything before try? On 2.12.1-fdroid at least it still is the case

**Comment by orionlee** [comment] 2024-05-26 14:35
The issue persisted with v2.12.2, on Pixel 3a (Android 12), Galaxy Tab S6 (Android 12), and Moto E4 (Android 7.1.1).
The settings screen shows as a separate entry in recent apps as well. I don't know if it's a regression or not.

**Comment by xxxxme** [comment] 2024-05-28 12:41
Also present for me in 2.12.1 and 2.12.2 on a Pixel 5a running crDroid 9.17 (A13).

**Comment by c-s-n** [comment] 2024-06-02 19:41
I can confirm the aforementioned findings: This is a regression that was introduced with 2.12.0, and did not exist in 2.11.1.
> Have you unchecked the multi window option and closed/swiped out everything before try?

The option was unchecked and the issue started appearing after the app update. Anyhow, I tried re-activating the Multiple Windows feature, closing everything. Then deactivating it again, closing everything. The issue still persists.

Pixel 7a, CalyxOS, Android 14.

**Comment by gsantner** [comment] 2024-06-02 19:50
merge requests are welcome

**Comment by gsantner** [comment] 2024-06-02 19:54
merge requests are welcome. the activity multi window vs single window, restarting, rotating and sharing into is not a simple thing to resolve for all cases and in dynamic (non compiletime constant/flag) way.

It's known in latest versions, just place a thumb up at the topic instead of repeating.

**Comment by harshad1** [comment] 2024-06-06 03:05
@c-s-n could you check if this is resolved on #2307

**Comment by hmmuaa** [comment] 2024-06-06 06:01
> I can confirm the aforementioned findings: This is a regression that was introduced with 2.12.0, and did not exist in 2.11.1.
> 
> > Have you unchecked the multi window option and closed/swiped out everything before try?
> 
> The option was unchecked and the issue started appearing after the app update. Anyhow, I tried re-activating the Multiple Windows feature, closing everything. Then deactivating it again, closing everything. The issue still persists.
> 
> Pixel 7a, CalyxOS, Android 14.

me too all the same @Android 13

**Comment by min7-i** [comment] 2024-06-11 21:23
> could you check if this is resolved on 2307

@harshad1 I tested the latest [artifact](https://github.com/gsantner/markor/actions/runs/9434625382) from your PR and the behavior is identical to 2.12.2. No matter if the multiple windows setting is enabled or disabled, multiple windows are still opened.

**Comment by tom22k** [comment] 2024-07-08 20:12
I can also reproduce this bug on my Fairphone 5 (Stock Android 13) on version 2.12.2. Despite having the Multiple Windows feature disabled, it is functionally always on.

**Comment by Asmageddon** [comment] 2024-07-12 08:16
Any ETA for this getting fixed? Considering it used to work correctly, surely something can be done?

**Comment by gsantner** [comment] 2024-07-12 14:06
No. Don't ask for ETA's in volunteer open source projects. Stuff gets done when a developer is both interested to give their time and has time.

 Please stop screaming metoo and if you are interested in getting it fixed, start development, fix it, and make a merge requedt. Thank you.

I for myself rather don't see a big issue by this, and would rather drop the settings option then making a complicated fix that in turn makes everything else more complicated/buggy.

For those asking for every little detail to be configurable, settings, and themeable - just again noting that every option comes at a cost. Also people rumble if suddenly a bit works differently. One of the reasons I don't like this micro detail options creep.

**Comment by harshad1** [comment] 2024-08-08 15:58
@gsantner I am making some improvements to the intent / window launching system.

When we have multiple windows enabled each new DialogActivity is launched separately. Should this behavior be true even if the intent for a new file came from an existing DocumentActivity? i.e. if I open a link to another file from a document, should that new document open on the current stack or on a new stack. This is with multiple windows enabled.

**Comment by gsantner** [comment] 2024-08-08 16:34
Thank you @harshad1 !

My view generally is this: You usually work with multiple tabs in Editors and IDEs on Desktop. Tabs don't work well on mobile. As alternative that works better we have switcher and windows...so it roughly translates to Tab=Window.

So regardless how you came to a file, it should be a own window. What would be good to have is that we don't have multiple windows for the same file - though I know that it is difficult the way Activities work. Multiple windows for same file might make issues with file management.

**Comment by gsantner** [comment] 2024-08-08 16:35
Thank you @harshad1 !

My view generally is this: You usually work with multiple tabs in Editors and IDEs on Desktop. Tabs don't work well on mobile. As alternative that works better we have switcher and windows...so it roughly translates to Tab=Window.

So regardless how you came to a file, it should be a own window. What would be good to have is that we don't have multiple windows for the same file - though I know that it is difficult the way Activities work. Multiple windows for same file might make issues with file management.

**Comment by harshad1** [comment] 2024-08-08 18:15
> it should be a own window

I tried doing this once with maintaining a Singleton map of which file was open in which activity, but it was super janky.

Imo the best workflow is

- open file from shortcut or file explorer: opens in new window
- follow link from file: open in same window

This is roughly the behavior we see from desktop text editors (neovim in my case) 

Will test more. But as you know it is impossible to make everyone happy 😆

**Comment by Asmageddon** [comment] 2024-08-15 13:40
> @gsantner I am making some improvements to the intent / window launching system.

Hey, if you're working on this, could you fit in a side quest of making within-markor links work properly? E.g. if I have a collection of links in my `Main.md`, for example to `TopicA/File1.md` and `TopicB/Overview.md`, I'd like to be able to click those links, and then navigate back to the previous file, as opposed to back going back to the directory where I opened the first(`Main.md`) file.

**Closed** 2024-09-19 00:39 UTC
Labels: bug
