### ISSUE TITLE
New line is being added occasionally to markdown files

### ISSUE THREAD

**Issue by oktayacikalin** [gsantner/markor#1676] opened 2022-04-24 14:03 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

I'm using a markdown file for capturing ideas, to-dos, pictures etc… Which I will later on import using syncthing into Obsidian on my laptop.
Every entry is a task. I've always an unchecked task ready to flesh out, If I need to. So my cursor is always at the end of the task line. I've also configured the app to always move the cursor to the end when opening a file.

### Steps to reproduce

1. Configure app to always start the cursor at the end of the file.
2. Create a markdown file and configure it as the QuickNote file.
3. Add some tasks to it, and leave the cursor at the last line right after "- [ ] ". (no new line / LF !)
4. Close the app.
5. Drop the app from memory or let it drop automatically by using other apps.
6. Reopen the QuickNote.
7. A LF has been appended, and the cursor is at the new line and not at the end of the empty task line.

### Information

Android version: 9
EMUI version: 9.1.0
Device: Honor 9 Lite
App Version: 2.8.0 (124)

### Source

Google Play

### Format / File type

Markdown

### Additional info / Log

```shell
-
```

**Comment by oktayacikalin** [comment] 2022-04-24 14:12
I've just tried to create a test.md file out of the syncthing folder, so that it cannot interfere.
It looks like a LF is being added as soon as I reopen the file. Is this intended? How can I turn this off?
It would also help if the on-screen-keyboard pops up right after reopening the file so that the cursor is at the task line. As of now, the keyboard does not come up after hitting the QuickNote button, and I have to touch the screen in order to get it. At that point, the cursor will be placed in the new empty line and not at the task line.

**Comment by gsantner** [comment] 2022-04-24 14:50
update to 2.8.6  
2.8.0 is outdated.

**Comment by oktayacikalin** [comment] 2022-04-24 19:44
Hmm.. looks like this came in with https://github.com/gsantner/markor/issues/635

If you want to keep this behavior, can we at least have an option to disable this?

**Comment by oktayacikalin** [comment] 2022-04-24 19:46
> update to 2.8.6 2.8.0 is outdated.

There is no 2.8.6 in the play store. But this doesn't even matter because of #635, which came in much earlier.

**Comment by gsantner** [comment] 2022-04-24 20:00
google play is not updated anymore.

![grafik](https://user-images.githubusercontent.com/6735650/164994332-2e18974e-3d38-4c64-955e-7f5742499ff7.png)

F-Droid has 2.8.6.

**Comment by oktayacikalin** [comment] 2022-04-24 20:10
I've just tested the 2.8.5 apk from GitHub and the LF seems not being added anymore. At least, I am not able to reproduce it in any way :-).

https://github.com/gsantner/markor/releases/tag/v2.8.6 does not have an apk. Where can I get it? 2.8.5 does have one.

I'm sorry, but when I visit the F-Droid store, it just offers me 2.8.0. Is my Android version too old?

**Comment by gsantner** [comment] 2022-04-24 20:12
Hmm, it should offer 2.8.6 (also listed on website). Required Android version has not been changed since start of the project, so nope

**Comment by oktayacikalin** [comment] 2022-04-24 20:13
Now I'm confused - visiting it on my linux laptop it lists 2.8.6 - but not on my smartphone. I'm taking a deeper look into it..

**Comment by oktayacikalin** [comment] 2022-04-24 20:28
I'm now on 2.8.6 via F-Droid. It looks like F-Droid didn't want to update the package installed from the play store. After uninstalling Markor, F-Droid offered me 2.8.6. Now it works fine.

Is it possible to have a note on the play store page in order to explain this to others coming from there? :-)

**Comment by gsantner** [comment] 2022-04-24 20:39
Thats why the template explicitley says updates are available from f-droid and github. it does not say google play.

it said 2.8.0 in the app then because of signature difference, fdroid uses their own signature, and gplay has other (my gsantner) signature, and for gsantner signature fdroid cannot update. however github just like gplay has gsantner signature, so thats the way to move on from gplay.

closing as the issue is fixed.

**Closed by gsantner** 2022-04-24 20:39 UTC

**Comment by oktayacikalin** [comment] 2022-04-24 20:44
Yeah - looks like you're right. Thank you for your fast support!
