### ISSUE TITLE
H1 heading at the start of a file doesn't render properly

### ISSUE THREAD

**Issue by P4ndemic** [gsantner/markor#837] opened 2020-01-22 23:07 UTC
#### General information
visual mode of md files sometimes doesn't display an H1 heading as a heading.
* **App version:** 
2.2.5
* **System:** 
Android 9, OnePlus3t, OxygenOs version 9.0.5

#### Description
The formatting should be correct, it's at the start of the file, with a space between the hash and the heading text.
# my_heading

It should be rendering all # text as headings h1.

Additionally those files were not created by Markor, it works fine if I type out a heading manually in say the TODO file. The effected files are all .md files. Only the heading on the very first line of the document is affected.
![image](https://user-images.githubusercontent.com/14100355/72942593-1ec5c680-3d74-11ea-8fc3-9c5c9a489304.png)

**Comment by gsantner** [comment] 2020-01-22 23:21
![Screenshot_20200123-001956_Markor](https://user-images.githubusercontent.com/6735650/72943369-cee40100-3d6d-11ea-9565-4a084187506e.png)
![Screenshot_20200123-002003_Markor](https://user-images.githubusercontent.com/6735650/72943370-cf7c9780-3d6d-11ea-8733-d0ab51b52344.png)


I can't spot any issue. are you sure this is a markdown file and not have disabled some markdown settings?

**Comment by P4ndemic** [comment] 2020-01-23 20:10
the file is a .md file and also registers as an md file when I check it's properties
![image](https://user-images.githubusercontent.com/14100355/73019873-bd116500-3e24-11ea-966e-74ff0da1ca51.png)

But maybe the extra dot in the filename is what causes the wrong rendering?

**Comment by P4ndemic** [comment] 2020-01-23 20:15
If it's helpful the h2 heading that is right below the h1 heading renders fine
![image](https://user-images.githubusercontent.com/14100355/73020089-3446f900-3e25-11ea-9a96-4f4e46039ca7.png)
![image](https://user-images.githubusercontent.com/14100355/73020198-6d7f6900-3e25-11ea-865f-eefa401442e4.png)

**Comment by gsantner** [comment] 2020-01-26 23:58
I'm sorry but I cannot reproduce this in any way. I created a file with exact same filename and same content and it looks fine. Also, I do something like that quite often, and have never seen an issue to be honest.


![out](https://user-images.githubusercontent.com/6735650/73143914-5fd11a00-4097-11ea-82b8-735eed24e91f.png)

I'm closing this as I see you have a idea how to get it working on your specific device.

**Closed by gsantner** 2020-01-26 23:58 UTC

**Comment by P4ndemic** [comment] 2020-02-11 12:51
For anyone else running into this issue, it is caused by using vimwiki with .md files. While the extension is .md the filetype internally is set to vimwiki to make some of it's functionality work. 

In the windows file info it will show filetype as MD, but if you open the file in vim you'll see the filetype is vimwiki.
