### ISSUE TITLE
Crash: after install markor 2.10.0 , if I don't give permission to markor, app will crash

### ISSUE THREAD

**Issue by XYIheng** [gsantner/markor#1763] opened 2022-07-21 06:44 UTC
# IMPORTANT
* App version: 2.10.0
* Android version/rom: 8.0
* Device: Google Pixel 2
* I accept that this issue will be closed without further notice in case I didn't describe the problem including general information, or didn't [search](https://github.com/gsantner/markor/issues?q=) for similar issues & [requests](https://github.com/gsantner/markor/discussions?discussions_q=).

## Explain the Problem
when I install the newest version 2.10.0, if I don't give storage permission to markor, it will crash.

see the bug video:

https://user-images.githubusercontent.com/31406320/180146864-fa530aae-39bc-4e0a-b402-6a4ac9d306ad.mp4

However, when I used version 2.8.1, this bug did not occur. 
see the normal behaviour with version 2.8.1:

https://user-images.githubusercontent.com/31406320/180146879-31165f69-8e96-46af-a4e0-4e95df0bdc6a.mp4

## Steps to Reproduce
1. install markor 2.10.0
2. open markor
3. click next to bypass the welcome pages
4. when it requires storage permission, click cancel.
5. click done
6. click ok
7. see the crash

## Log
<details>
<summary>Log</summary>
crash trace:
07-21 06:17:50.122  1706  1706 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
07-21 06:17:50.122  1706  1706 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.net.NetworkPolicyManagerService.bindNotificationManager(android.app.INotificationManager)' on a null object reference
07-21 06:17:50.122  1706  1706 E AndroidRuntime: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1156)
07-21 06:17:50.122  1706  1706 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:396)
07-21 06:17:50.122  1706  1706 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:260)
07-21 06:17:50.122  1706  1706 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-21 06:17:50.122  1706  1706 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-21 06:17:50.122  1706  1706 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: FATAL EXCEPTION: main
07-21 06:18:30.242  4327  4327 E AndroidRuntime: Process: net.gsantner.markor, PID: 4327
07-21 06:18:30.242  4327  4327 E AndroidRuntime: java.lang.IllegalArgumentException: Receiver not registered: android.support.v7.app.AppCompatDelegateImpl$AutoNightModeManager$1@5c50885
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1175)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1433)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:639)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:639)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:639)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImpl$AutoNightModeManager.cleanup(AppCompatDelegateImpl.java:2720)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImpl.onStop(AppCompatDelegateImpl.java:443)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at android.support.v7.app.AppCompatDialog.onStop(AppCompatDialog.java:134)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at android.app.Dialog.dismissDialog(Dialog.java:378)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at android.app.Dialog.dismiss(Dialog.java:354)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:171)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
07-21 06:18:30.242  4327  4327 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```
Paste log here
```
</details>

**Comment by harshad1** [comment] 2022-07-25 17:58
Hmmm. I can't reproduce this on a pixel 3xl + android 12

**Comment by gsantner** [comment] 2022-07-26 22:09
I could reproduce, but at PR #1521 it's fixed

**Comment by gsantner** [comment] 2022-08-06 12:36
fixed on master branch, can't reproduce anymore.

**Closed by gsantner** 2022-08-06 12:36 UTC
