### ISSUE TITLE
Editor goes to bottom of file, always

### ISSUE THREAD

**Issue by Sepero** [gsantner/markor#1790] opened 2022-08-15 04:23 UTC
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**. Not a question or feature request.
- [X] The issue is **not** already reported at [Issues](https://github.com/gsantner/markor/issues?q=) or [discussions](https://github.com/gsantner/markor/discussions?discussions_q=). _(I've searched it)_.
- [X] Markor **is** up to date. See [Releases](https://github.com/gsantner/markor/tags) for the latest version. Updates are available from [F-Droid](https://f-droid.org/en/packages/net.gsantner.markor/) and GitHub.

### Description

Opening files goes to the end of the file, instead of the cursor remaining at last position

Began experiencing this after upgrading to version 2.10.0

Attempt to resolve

1. Turning on the option "Start on bottom"
2. Force quit app
3. Turning off the option "Start on bottom"
4. Force quit app
5. Still starting at bottom of file

I uninstalled and reinstalled previous version 2.9.0 from Fdroid. The issue does not exist in 2.9.0

### Steps to reproduce

Close and reopen any text (txt) file.

### Information

Android version: 10
Device: OnePlus 6
App Version: 2.10.0

### Source

F-Droid

### Format / File type

Plaintext

### Additional info / Log

```shell
-
```

**Comment by gsantner** [comment] 2022-08-15 09:05
At which file? QuickNote and ToDo on the main screen always start on bottom regardless of the setting. So you can start adding new todos immediatly.

Otherwise, the setting should work fine.

**Comment by crasm** [comment] 2022-08-15 13:11
I was getting this for a time, but I reinstalled (and switched to F-Droid) and it seems to be behaving as expected now.

**Comment by Sepero** [comment] 2022-08-16 18:10
@gsantner 
It was happening with files I created.

@crasm
I've only been using the Fdroid app. Do you remember which version(s) you were having the issue with?

Thank you for the quick replies

**Comment by harshad1** [comment] 2022-08-18 06:54
Note: 

The two available behaviors are
1. Open at bottom
2. Open at last cursor position

**Comment by crasm** [comment] 2022-08-20 04:51
I had switched from the Google Play version to the F-Droid one (2.10.1) because I had some serious editing performance regressions with my text files with the 2.10.0 update.

The performance problem cleared up, but I'm getting shunted to the bottom of my journal text file instead of the top (last known position) when accessing files from the homescreen shortcut feature.

**Comment by gsantner** [comment] 2022-08-20 04:52
Have you checked the Markor settings?

**Comment by crasm** [comment] 2022-08-20 04:55
@gsantner Yes, it seems to work just fine remembering the position when opening from the Markor app file picker.

**Comment by harshad1** [comment] 2022-08-20 05:08
We changed the behavior to open todo and quicknote at the bottom from the shortcuts and widget too..

If this is not desirable we could either remove it or make it an option.

Also there is a fix for the play store version performance issues in the works.

Aug. 19, 2022 21:55:52 Christian Demsar ***@***.***>:

**Comment by crasm** [comment] 2022-08-20 05:19
Well it'd certainly be more convenient for me. I think it'd also satisfy the principle of least astonishment by keeping the behavior consistent.

Most of my files are tail-append, but my daily journal from 2020 is head-append.

...

I can't reproduce the bug via regular access as described in this issue, however. Wonder if it's device/platform related.

**Comment by gsantner** [comment] 2022-08-20 05:25
Closing as there you generally have a settings option. and for quicknote there is a very specific reason - that you append things there by sharing stuff into markor - or by adding things **quick** on your own. if you need to scroll up, do that. and for all other files, theres the settings option.

and the mentioned performance is a completely different topic, please comment on the right issue/discussion. thanks!

**Closed by gsantner** 2022-08-20 05:25 UTC

**Comment by harshad1** [comment] 2022-08-20 05:28
To be clear, a file shortcut will open at the last known position (unless the always at bottom option is checked). The default shortcuts to quicknote and todo from the widget and the launcher will open at the bottom always, as this is the point of quicknote / todo.

**Comment by Sepero** [comment] 2022-08-20 14:01
> We changed the behavior to open todo and quicknote at the bottom from the shortcuts and widget too.. 

This is probably the issue for me, because I ALWAYS open files from widget/shortcuts. I have several of them in a folder together. I need to start at the last edited position.

**Comment by Sepero** [comment] 2022-08-20 14:03
If this is not desirable we could either remove it or make it an option.

Yes, please do this. For now I am stuck on Markor v2.9.0

**Comment by gsantner** [comment] 2022-08-20 16:55
You may also just use some other file then QuickNote from the launcher if you don't want starting on bottom. The next time you start markor the new saved location will be anyway bottom-most again.

**Comment by gsantner** [comment] 2022-08-20 17:00
You may also just use some other file then QuickNote from the launcher if you don't want starting on bottom. The next time you start markor the new saved location will be anyway bottom-most again.

Really just saying WHY it is like it is: Your cursor is somewhere, when you leave, maybe at the end, maybe not. Then you append some 2 links by i.e. Sharing into Markor, and so the saved cursor is somewhere in the the middle of content. When you start Markor then next time you just can't start typing new things, you have to scroll first, put your cursor at the end, press enter. And this is WHY QuickNote always starts on bottom. Otherwise it would not be **QUICK**note .

So really, if you don't want the way QuickNote works, don't use it. But I don't want to have a settings option for everything. The settings are already bloated, just for the reason of specialized user needs most other users don't have.

**Comment by crasm** [comment] 2022-08-20 17:10
I am not using quicknote, but the "create a shortcut" on homescreen function. I didn't think those were equivalent? If the old behavior was restored I would very much appreciate it

**Comment by gsantner** [comment] 2022-08-20 17:13
What I read in this thread, there are different usage for you and Sepero. With no word I read "create a shortcut" here yet. So giving more input is totally helpful, just saying "me too" is often not helpful as it might be some different issue/case/problem/reason.

**Comment by gsantner** [comment] 2022-08-20 17:18
What will be probably be a resulting point at some time: that the cursor position setting is per-file based in addition to global, similar like linewrap.

**Comment by harshad1** [comment] 2022-08-20 17:21
I am looking into this rn and it looks like other shortcuts are being opened at the bottom too... Will create a fix today

**Comment by Sepero** [comment] 2022-08-20 19:08
> You may also just use some other file then QuickNote from the launcher if you don't want starting on bottom there.

I too am not using QuickNote, nor Todo. I have my own files.

I appreciate the quick replies and attention to this issue. Please reopen this issue so that it can properly be closed after a fix has been released.

**Comment by Sepero** [comment] 2022-08-23 20:03
> I am looking into this rn and it looks like other shortcuts are being opened at the bottom too... Will create a fix today

Has this issue been resolved in v2.10.3?

**Comment by gsantner** [comment] 2022-08-23 20:30
Try it.

**Comment by lmagyar** [comment] 2022-08-30 18:29
This issue should be reopened.

> To be clear, a file shortcut will open at the last known position (unless the always at bottom option is checked). The default shortcuts to quicknote and todo from the widget and the launcher will open at the bottom always, as this is the point of quicknote / todo.

It's simply not true. Shortcuts (and external browsers) open ALL files at the bottom (in case of v2.9 at the top). I use plain text files on SD card. And yes, the option is turned off in the settings. It NEVER remembers the last position.

The only way to remember the last position is opening the file from Markor file browser. But if I exit the browser and restart it, then reopen the file, it can't remember the position.

All these "smart" features (remembering the position, detecting whether it is a plain text file or a Todo) are simply never working.

I've downgraded to v2.9, that version at least opens the files at the top.

Android 8, SM-A320FL

**Comment by Sepero** [comment] 2022-09-06 20:24
I just finished installing and testing v2.10.3 and the issue persists. When clicking on a file shortcut, it jumps to the end of the file.

**Comment by Sepero** [comment] 2022-09-06 20:35
Attached is a video demonstration of the issue. I'm not using QuickNote nor Todo. When opening the file, it jumps to the bottom every time. This issue does not exist in v2.9.0, and first appeared in v2.10.0


https://user-images.githubusercontent.com/1575546/188732463-877478a0-8dbd-43d2-9f0d-499e5409d910.mp4

**Comment by Sepero** [comment] 2022-09-08 19:05
> Closing as there you generally have a settings option. and for quicknote there is a very specific reason - that you append things there by sharing stuff into markor - or by adding things **quick** on your own. if you need to scroll up, do that. and for all other files, theres the settings option.
> 
> and the mentioned performance is a completely different topic, please comment on the right issue/discussion. thanks!

@gsantner 
This issue has nothing to do with QuickNote. It is affecting other files. And it has nothing to do with performance. I am the OP of this issue, and not the person you replied to. I have appended further information to demonstrate the problem.

Why do you continue to ignore my requests to re-open? Have I made a mistake? Have I offended you? This issue continues to persist. If I have done something wrong, then I sincerely apologize. I'm trying to follow protocol.

I'm asking for a third time to Please re-open this issue.

**Comment by harshad1** [comment] 2022-09-08 19:33
This issue has been fixed. The fix hasn't been released yet. My understanding is that @gsantner will release it soon.

**Comment by gsantner** [comment] 2022-09-08 19:33
@Sepero   
Please understand that all I do here is by my free, leisure, after-work time. This is not a company project.

Please deal with some basic how open source community & development works. And not works. By repeating you don't make something better, neither by crying to do something or by forcing to reopen something. Be it closed or open or whatever is just the matter of a indicator.  It not means that it gets done, not that it gets fixed, not that it's not done. You are not the boss, and neither my customer, so don't act like that. Being patient is key. My time is limited and as such time Thanks.

> I'm asking for a third time to Please re-open this issue.

Don't repeat. 

> Why do you continue to ignore my requests to re-open?

Because it's fixed/improved in development version and I'm not a fan of these "I'm the boss, do it now" discussions. And even if it's not fixed, don't act this way thanks. I get much questions and emails regarding this topic and I'm really tried of this topic.

When you really want to help, please do one thing - contribute code to the project (development), fixing issues yourself and implementing features yourself. If you don't know how to code, not a big problem, if you are interested in it you can learn it.

**Comment by gsantner** [comment] 2022-09-08 19:52
@Sepero   
Please understand that all done here is by free, leisure, after-work time. This is not a company project.

By repeating you don't make something better, neither by crying and forcing to reopen something. Be it closed or open is just a indicator.  It not means that it gets done, not that it gets fixed, not that it's not done. You are not the boss and neither a customer, so don't act like that. Being patient is key. Thanks.

> I'm asking for a third time to Please re-open this issue.

You don't get a higher priority because you repeat. Generally said, there is no set priority in anything here. Contributors, myself included, do what we find most important at the time, and when we have time. 

> Why do you continue to ignore my requests to re-open?

Because it's fixed/improved in development version and I'm not a fan of these "I'm the boss, do it now, I'm the most important one here" discussions. And even if it's not fixed, don't act this way thanks. I get much questions and emails regarding this topic and I'm really tried of this topic.

When you really want to help, please do one thing - contribute code to the project (development), fixing issues yourself and implementing features yourself. If you don't know how to code, not a big problem, if you are interested in it you can learn it. A lot better used time then repeating.

---

Thanks also to @harshad1 giving and his precious time for this

**Comment by Sepero** [comment] 2022-09-10 04:59
I understand that the developers here are unpaid, as I too am an unpaid FLOSS developer. Unfortunately, my proficiency is in other languages, and not specific to Android.

I apologize for crying and forcing, with my requests to re-open this issue. As I have my own projects, it is standard for me to never close an issue until it has been thoroughly fixed, because this ensures that others with the same issue can easily find it, add their contributions, and not open duplicate issues.

It was wrong for me to press my standards on your project. And I apologize for acting as a boss, or a customer, or other, in that way.

When the fix was not yet in 2.10.3, I asked if this issue has been fixed. I was given instruction to "Try it", while the dev knowing full well that the fix had not been released.

In good faith I accepted to test 2.10.3, also unpaid. Testing cost me about 2 hours of down time, as after app upgrade, an app must be fully uninstalled on Android to downgrade. And version 2.9.0 is no longer available in Fdroid, so it requires being discovered online. Yes, that lost time could have been lot better used with contributing to FLOSS projects.

This is the second time I've had to exhaust time downgrading since the issue first appeared. Markor has become vital to my workflow, so having to repeatedly reinstall is not a minor disruption for me (That's my problem, and I understand).

Just because you may not know how to code in Rust or Haskell, you are still indirectly contributing to it as other devs use Markor. Likewise, even though I don't develop for Android, it may be possible that you, or a project you depend on, is dependent on my code. We are all in a big FLOSS development circle here, and all dependent on one another. I want to respect you. As developers and contributors each in our own field, I ask that we are kind and respect one another.

Again, yes, very much thanks and gratitude to @harshad1 for his contributions. And thank you too @gsantner, for I know you have put tireless hours into the development of Markor for a long time. I'm very grateful and thankful for the work you've done.

**Comment by keithfancher** [comment] 2022-12-31 01:09
I was just coming here to file a bug about this, glad I found this conversation!

> We changed the behavior to open todo and quicknote at the bottom from the shortcuts and widget too..
>
> If this is not desirable we could either remove it or make it an option.

This seems logical to me for _quicknote_, but not for todo. I spend a lot more time _checking_ my todo list than I do appending to it. (Hopefully that's true for most people, or we'll never get to the end of our todos :smile:.)

And my most important todo items are at the _top_ of the list, of course. So every time I use the widget to open my todo list, I have to scroll back up to the top, because it defaults to showing me the bottom of my list.

I'd love an option to turn this behavior off, personally. My cursor's always at the end of my quicknote file anyway, since I pretty much only ever append to it, so that works out well for me either way. And if nothing else, I'd vote for it to be consistent with how files are opened anywhere else in the app. The fact that this _only_ happens when launching from the widget makes it feel like a bug.

I'd be curious what other folks think about this. To sum up, my suggestions are to do one of the following:

1. Add an _option_ to always start at the end for quicknote/todo, OR
2. Make it always start at the end for quicknote, but _not_ todo, OR
3. Just make the cursor start behavior consistent regardless of how the file is opened.

Thanks!

**Comment by harshad1** [comment] 2023-01-02 00:13
>  The fact that this only happens when launching from the widget makes it feel like a bug

It happens when launching todo from any place that is not the main file explorer. i.e.
* The widget
* The todo home screen shortcut (long press the main markor icon)
* The tabs in the main UI (but only when first opened)

When using todo there are workflows:
1. Adding items where you do want to be at the bottom
2. Actually trying to determine which tasks to do today / now 

I (we) chose to optimize for #1 because it is important to be able to capture very fast. Parsing the todo list usually takes a little longer anyway. Note that you can see the first task fast by:
* dragging the scroll bar
* long pressing the keyboard icon
* hitting search - it will show the tasks starting from the top

Also note that my usual workflow is to open todo and view a saved filter (such as `@pc` or `@sitting & @short`).

I have found that adapting my workflow to an app rather than the other way around can be sufficient. Please try these approaches and let me know what you think.

**Comment by nikolaos-spyratos** [comment] 2023-01-03 11:28
Happy new year to all!

I'm having this issue on custom files opened in the app - no widgets or shortcuts. v2.10.6 off of FDroid. Checking the release commits for the last few releases where this fix would've been put in according to harshad1's message, I don't see anything that would point to this fix being included. Same with PRs going back to Aug 15 when this issue was filed. If I am just being blind or it's still coming in a future release, please let me know.

I keep my journal and expense tracking with latest sections near the top of the file, so for long-running files it'd take a few minutes to scroll all way to the top. I also include templates and "static" info at the top of the file that belongs in each section, so it's more convenient to have the latest entries near the templates instead of jumping up and down or rewiring several years of files.

While I appreciate "change your workflow" may be viable, on the face of it purely for this issue it seems it's still present.

FWIW: Samsung A32, Android 13.

**Comment by harshad1** [comment] 2023-01-03 21:43
> this fix

Could you clarify what you're looking for a fix for? If you mean regular files always opening at the bottom then it appears to work fine for me on the latest master.

>  it'd take a few minutes to scroll all way to the top

Please read my message above. We have multiple ways of jumping quickly to the top of a file

**Comment by keithfancher** [comment] 2023-01-03 23:43
> I (we) chose to optimize for #1 because it is important to be able to capture very fast.

Ah, yeah, I can understand that. I actually tend to add my todo items near the top of the list.

> I have found that adapting my workflow to an app rather than the other way around can be sufficient. Please try these approaches and let me know what you think.

Indeed! I've changed my workflow to jibe better with Markor. Here are the two simple workarounds I do for my todo list, in case anybody else finds it useful:

1. I stopped using `todo.txt`, since I found the delay to parse the file pretty jarring. (Mentioned this in [this discussion](https://github.com/gsantner/markor/issues/963#issuecomment-1352174408), but I'm not sure if that was the right place for it.) Instead, I just use a regular markdown checklist.
2. I started listing my todo items in reverse order, with most important items on the bottom of the list. Now I can use the widget button again without having to scroll all the way up every time. (Handy "scroll all the way up" buttons aside, it's still an extra step.)

I honestly still find it a little un-intuitive that a given file will open with the cursor in a different position depending on whether I click it from the widget, home screen, etc. Adds a bit of cognitive overhead to some pretty simple operations. But it's definitely not a big deal.

I'm not demanding change or anything, just figured it'd be useful for the creators to hear from some users about their usage patterns :smile:

**Comment by harshad1** [comment] 2023-01-03 23:50
The delay is actually a settings. You can (mostly) eliminate it in settings. See the discussion you linked to.

**Comment by keithfancher** [comment] 2023-01-03 23:51
> Note:
>
> The two available behaviors are
> 
> Open at bottom
> Open at last cursor position

It just occurred to me: it might make _everybody_ happy just to round out this set of options with the third, missing choice, i.e. it could be a set of radio options like:

- Current default behavior
- Always open at bottom of file
- Always open at top of file

It does seem to be a natural fit.

> But I don't want to have a settings option for everything. The settings are already bloated, just for the reason of specialized user needs most other users don't have.

I definitely get this sentiment! But for what it's worth, as a user at least, I don't find the settings to be bloated. In fact, I find that Markor really hits the sweet spot of default usability and customizability. A change like the above doesn't seem like it will be "bloat" so much as rounding out an existing option.

In any case, thanks for the hard work! Markor's one of my favorite apps, which is why I'm here chiming in :D

**Comment by red-kite** [comment] 2023-02-09 20:20
> At which file? QuickNote and ToDo on the main screen always start on bottom regardless of the setting.

I've been wondering about the setting to 'start at bottom' being broken/useless for such a long time. Now glad to read about this being intended.

I very appreciate this powerful texteditor for android (being deeply grateful!) and also the user-selectable QuickNote/file opening at startup. Adding new content at the top of longer log-files for many years really made me tired of endless wiping at every of sometimes many notes per day.

Previously I intended to throw an issue. Now having found this thread, I will explore for alternative option (adding shortcut to a file instead of the application launcher) and follow this thread…

**Comment by ryanwwest** [comment] 2023-04-11 03:23
I'd like to add my vote to @keithfancher's comment. And while I understand that many might prefer to open a quick note at the bottom, in my case I use it to open my 'quick note' from my Obsidian vault, and when it's opened in Obsidian, it's always opened at the top. This is still fast for me. All of my notes are thus updated by adding new lines _at the top_, and older entries are found by scrolling. Not everyone does it like this, but I feel like many would appreciate having the option to control it.

Even if this isn't added, I think the Settings -> Edit mode -> Start on bottom setting should clarify its description so users don't get confused when QuickNote doesn't follow the setting.

**Comment by harshad1** [comment] 2023-04-11 22:41
You can create a homescreen shortcut to the quicknote file (long press your file in the browser).

This shortcut will remember the cursor position. If you always edit near the top your file will open at the top.

The document will also open without the tab UI, giving you some extra space.

Also note that you can drag the scroll bar to get around a document very fast.

**Comment by ryanwwest** [comment] 2023-04-11 23:18
@harshad1 Thank you, that's much better for my use case!

**Comment by lmagyar** [comment] 2025-04-13 10:22
v2.14.1 can't remember position again, jumps to the end always. Downgraded to v2.14.0, that remembers position.

This is a plain text file on SD card, opened through a shortcut.
